In [52]:
#import what we need 
import pandas as pd
import os
import sys, argparse, csv
import numpy as np

In [180]:
#read csv file with pandas
data_frame=pd.read_csv(r"C:\Users\Federico\Dropbox\5 tecnicas de program\lavoro di gruppo\dataset.csv",";") 
type(data_frame)
data_frame.infer_objects()

,code name,Company Common Name,Instrument Type,Asset Category Code,ISIN Code,Exchange Name,Ticker Symbol,Currency Code,Country of Headquarters,TRBC Business Sector Name,...,"Capital Expenditures, Cumulative","Cash from Investing Activities, Cumulative","Cash from Financing Activities, Cumulative",debt to asset ratio,equity to asset ratio,debt to equity ratio,Roa return on asset,roe return on equity,long term coverage ratio,asset turnover rate
0,SIEGn.DE,Siemens AG,Ordinary Shares,ORD,DE0007236101,XETRA,SIE,EUR,Germany,Industrial Conglomerates,...,-2602000000,-3774000000,-1946000000,"0,420100378","0,704396183","2,054889715","0,089952909","0,089952909","3,062094395","1,286387013"
1,AIR.PA,Airbus SE,Ordinary Shares,ORD,NL0000235190,NYSE EURONEXT - EURONEXT PARIS,AIR,EUR,Netherlands,Industrial Goods,...,-2558000000,-2530000000,321000000,"0,260597251","0,192742543","9,190782123","0,042371056","0,042371056","4,064596102","1,059222569"
2,SCHN.PA,Schneider Electric SE,Ordinary Shares,ORD,FR0000121972,NYSE EURONEXT - EURONEXT PARIS,SU,EUR,France,Industrial Goods,...,-749000000,-1238000000,-1522000000,"0,422366749","1,479928235","1,01288074","0,16072363","0,16072363","4,379292035","1,849667339"
3,SGEF.PA,Vinci SA,Ordinary Shares,ORD,FR0000125486,NYSE EURONEXT - EURONEXT PARIS,DG,EUR,France,Industrial & Commercial Services,...,-1920000000,-3046000000,-1200000000,"0,633353631","0,677842898","2,919094941","0,104582128","0,104582128","2,456195169","1,555640128"
4,SAF.PA,Safran SA,Ordinary Shares,ORD,FR0000073272,NYSE EURONEXT - EURONEXT PARIS,SAF,EUR,France,Industrial Goods,...,-1089000000,-334000000,393000000,"0,203770965","0,499252217","2,464748048","0,243029591","0,243029591","4,292529489","0,874692875"
5,DPWGn.DE,Deutsche Post AG,Ordinary Shares,ORD,DE0005552004,XETRA,DPW,EUR,Germany,Transportation,...,-2203000000,-2091000000,-1087000000,"0,34846842","0,856397398","2,060219989","0,183857414","0,183857414","11,75495916","4,096232041"
6,SGOB.PA,Compagnie de Saint Gobain SA,Ordinary Shares,ORD,FR0000125007,NYSE EURONEXT - EURONEXT PARIS,SGO,EUR,France,Cyclical Consumer Products,...,-1722000000,-2033000000,-1117000000,"0,622398105","1,135859404","1,506693734","0,097594416","0,097594416","4,086312206","2,543312975"
7,LHAG.DE,Deutsche Lufthansa AG,Ordinary Shares,ORD,DE0008232125,XETRA,LHA,EUR,Germany,Transportation,...,-3338000000,-5006000000,-245000000,"0,556895457","0,816665155","2,97224381","0,212167921","0,212167921","5,792738522","3,225949769"
8,BOUY.PA,Bouygues SA,Ordinary Shares,ORD,FR0000120503,NYSE EURONEXT - EURONEXT PARIS,EN,EUR,France,Industrial & Commercial Services,...,-1931000000,-1481000000,-362000000,"0,309728834","0,483393058","3,016707236","0,057870247","0,057870247","5,685201174","1,760870728"
9,MTXGn.DE,MTU Aero Engines AG,Ordinary Shares,ORD,DE000A0D9PT0,XETRA,MTX,EUR,Germany,Industrial Goods,...,-305000000,-340800000,-332900000,"0,331296117","0,672654096","2,448864266","0,132332116","0,132332116","4,384026997","1,45241112"
10,TCFP.PA,Thales SA,Ordinary Shares,ORD,FR0000121329,NYSE EURONEXT - EURONEXT PARIS,HO,EUR,France,Industrial Goods,...,-438900000,-607700000,-381200000,"0,064297949","0,331888006","3,764552898","0,045841369","0,045841369","15,97011012","1,026845321"
11,WLSNc.AS,Wolters Kluwer NV,Ordinary Shares,ORD,NL0000395903,NYSE EURONEXT - EURONEXT AMSTERDAM,WKL,EUR,Netherlands,Industrial & Commercial Services,...,-210000000,-409000000,-60000000,"0,765613243","0,838224229","2,80475763","0,239277652","0,239277652","2,146437346","1,643340858"
12,LEGD.PA,Legrand SA,Ordinary Shares,ORD,FR0010307819,NYSE EURONEXT - EURONEXT PARIS,LR,EUR,France,Industrial Goods,...,-144600000,-1802100000,887400000,"1,017747581","1,704179535","1,277171024","0,292855672","0,292855672","2,233694773","2,273337451"
13,FER.MC,Ferrovial SA,Ordinary Shares,ORD,ES0118900010,BOLSA DE MADRID,FER,EUR,Spain,Industrial & Commercial Services,...,-135000000,-468000000,324000000,"0,931663153","0,68250031","3,177721243","0,056182562","0,056182562","0,685835996","0,638968126"
14,TEPRF.PA,Teleperformance SE,Ordinary Shares,ORD,FR0000051807,NYSE EURONEXT - EURONEXT PARIS,TEP,EUR,France,Industrial & Commercial Services,...,-148000000,-151000000,-453000000,"1,009461426","1,390101892","1,35078534","0,227074236","0,227074236","3,01369863","3,042212518"
15,AIRF.PA,Air France KLM SA,Ordinary Shares,ORD,FR0000031122,NYSE EURONEXT - EURONEXT PARIS,AF,EUR,France,Transportation,...,-2552000000,-2692000000,-640000000,"1,088430117","0,265842349","11,44310631","0,017995142","0,017995142","2,623694087","2,855707662"
16,ALSO.PA,Alstom SA,Ordinary Shares,ORD,FR0010220475,NYSE EURONEXT - EURONEXT PARIS,ALO,EUR,France,Industrial Goods,...,-293000000,-353000000,-305000000,"0,166499785","0,482906594","2,923578199","0,052209984","0,052209984","6,310996564","1,050779574"
17,SGREN.MC,Siemens Gamesa Renewable Energy SA,Ordinary Shares,ORD,ES0143416115,BOLSA DE MADRID,SGRE,EUR,Spain,Renewable Energy,...,-415076000,-417252000,501758000,"0,112079532","0,806754732","1,725860905","0,009531935","0,009531935","11,08417011","1,242308593"
18,LIGHT.AS,Signify NV,Ordinary Shares,ORD,NL0011821392,NYSE EURONEXT - EURONEXT AMSTERDAM,LIGHT,EUR,Netherlands,Cyclical Consumer Products,...,-96000000,-26000000,-484000000,"0,346975089","0,664887307","1,978590544","0,086892052","0,086892052","5,952991453","2,065539739"
19,ACS.MC,ACS Actividades de Construccion y Servicios SA,Ordinary Shares,ORD,ES0167050915,BOLSA DE MADRID,ACS,EUR,Spain,Industrial & Commercial Services,...,-635744000,-301882000,-477948000,"0,250107324","0,181395346","7,373091042","0,0388687","0,0388687","6,762340207","1,691310812"
20,RAND.AS,Randstad NV,Ordinary Shares,ORD,NL0000379121,NYSE EURONEXT - EURONEXT AMSTERDAM,RAND,EUR,Netherlands,Industrial & Commercial Services,...,-107300000,-457400000,-557200000,"0,12574968","0,835906007","1,296612562","0,124156917","0,124156917","36,39218139","4,576305181"
21,RHMG.DE,Rheinmetall AG,Ordinary Shares,ORD,DE0007030009,XETRA,RHM,EUR,Germany,Automobiles & Auto Parts,...,-270000000,-189000000,-200000000,"0,164651698","0,528497409","2,369281046","0,064478987","0,064478987","10,30769231","1,697179044"
22,FOUG.PA,Eiffage SA,Ordinary Shares,ORD,FR0000130452,NYSE EURONEXT - EURONEXT PARIS,FGR,EUR,France,Industrial & Commercial Services,...,-595000000,-598000000,-663000000,"1,032282794","0,365417376","5,999067599","0,046678024","0,046678024","1,268091427","1,309028961"
23,IMCD.AS,IMCD NV,Ordinary Shares,ORD,NL0010801007,NYSE EURONEXT - EURONEXT AMSTERDAM,IMCD,EUR,Netherlands,Chemicals,...,-12814000,-181380000,95977000,"0,552039859","1,106633906","1,268628777","0,117255865","0,117255865","5,243599295","2,894675817"
24,GETP.PA,Getlink SE,Ordinary Shares,ORD,FR0010533075,NYSE EURONEXT - EURONEXT PARIS,GET,EUR,France,Transportation,...,-275240000,-277109000,16002000,"5,482904289","2,665109105","2,652707541","0,146745168","0,146745168","0,244808898","1,342263757"
25,AENA.MC,Aena SME SA,Ordinary Shares,ORD,ES0105046009,BOLSA DE MADRID,AENA,EUR,Spain,Transportation,...,-370409000,-361614000,-1364274000,"5,99422822","4,681384733","1,693814169","1,014967413","1,014967413","0,544333877","3,262861488"
26,BNRGn.DE,Brenntag AG,Ordinary Shares,ORD,DE000A1DAHH0,XETRA,BNR,EUR,Germany,Chemicals,...,-151400000,-244900000,-224300000,"0,430860966","0,864805119","1,450154715","0,104944735","0,104944735","7,927698643","3,415735893"
27,EDEN.PA,Edenred SA,Ordinary Shares,ORD,FR0010908533,NYSE EURONEXT - EURONEXT PARIS,EDEN,EUR,France,Industrial & Commercial Services,...,-78000000,-176000000,-264000000,"0,384513858","-0,33150022","-5,121433311","0,053013638","0,053013638","0,755148741","0,290365156"
28,BICP.PA,Societe BIC SA,Ordinary Shares,ORD,FR0000120966,NYSE EURONEXT - EURONEXT PARIS,BB,EUR,France,Industrial & Commercial Services,...,-174811000,-111761000,-275358000,"0,000181478","1,436775933","0,382783153","0,242541033","0,242541033","9494,92093","1,723121595"
29,OSRn.DE,Osram Licht AG,Ordinary Shares,ORD,DE000LED4000,XETRA,OSR,EUR,Germany,Industrial Goods,...,-467000000,-625000000,72000000,"0,076612903","1,278225806","0,865141956","0,069052419","0,069052419","27,07236842","2,074092742"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,RKB1R.RI,Rigas Kugu Buvetava AS,Ordinary Shares,ORD,LV0000100378,NASDAQ OMX RIGA,RKB1R,EUR,Latvia,Industrial Goods,...,-303440,-294730,2383290,"0,435738208","4,951701977","0,443372407","-0,049844025","-0,049844025","4,770337024","2,078618107"
523,DKRr.AT,Domiki Kritis SA,Ordinary Shares,ORD,GRS364253005,ATHENS EXCHANGE S.A. CASH MARKET,DOMIK,EUR,Greece,Industrial & Commercial Services,...,-242470,-173810,339400,"0,525637912","1,514911649","1,896483891","-0,329478955","-0,329478955","2,529853992","1,329787169"
524,VOGr.AT,Vogiatzoglou Systems SA,Ordinary Shares,ORD,GRS407183003,ATHENS EXCHANGE S.A. CASH MARKET,VOSYS,EUR,Greece,Cyclical Consumer Products,...,-534000,-512000,-184000,"0,081815057","1,03616363","0,441045717","0,103609488","0,103609488","18,07058824","1,478446201"
525,XYLr.AT,Interwood Xylemporia ATENE,Ordinary Shares,ORD,GRS131003006,ATHENS EXCHANGE S.A. CASH MARKET,XYLEK,EUR,Greece,Applied Resources,...,-253790,-210120,1734310,"0,50487372","0,391038603","3,181782179","-0,007586613","-0,007586613","1,815137962","0,916415454"
526,MLVAL.EUA,Valoneo SASU,Ordinary Shares,ORD,FR0012833770,NYSE EURONEXT - MARCHE LIBRE PARIS,MLVAL,Unable to collect data for the field 'TR.COMPA...,France,Industrial & Commercial Services,...,Unable to collect data for the field 'TR.Capit...,Unable to collect data for the field 'TR.CashF...,Unable to collect data for the field 'TR.CashF...,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
527,CETG.LJ,Cetis dd,Ordinary Shares,ORD,SI0031100843,LJUBLJANA STOCK EXCHANGE (OFFICIAL MARKET),CETG,EUR,Slovenia,Industrial & Commercial Services,...,-5317050,-4792840,-2814700,"0,254009847","1,412506456","0,70138936","0,163474451","0,163474451","10,00891386","2,542362673"
528,URBA.SCT,Urbar Ingenieros SA,Ordinary Shares,ORD,ES0182484214,BOLSA DE MADRID,UIN,EUR,Spain,Mineral Resources,...,-13160,-13160,-104720,#VALORE!,"0,038378611","94,42696629","-0,512656317","-0,512656317",#VALORE!,"1,557171194"
529,GCEr.AT,AEGEK SA,Ordinary Shares,ORD,GRS182003004,ATHENS EXCHANGE S.A. CASH MARKET,AEGEK,EUR,Greece,Industrial & Commercial Services,...,-270,427490,-36697250,0,"-0,860205551","-2,825298479","-0,222405174","-0,222405174",#DIV/0!,"0,643919699"
530,PWBP.EUA,Phone Web SA,Ordinary Shares,ORD,FR0000185480,NYSE EURONEXT - MARCHE LIBRE PARIS,MLPHW,EUR,France,Cyclical Consumer Services,...,NaN,NaN,NaN,"0,006303448","0,639829132","0,70176603","-0,022207789","-0,022207789","260,2324967","1,640362053"
531,1ZTS01NE.BV,ZTS Sabinov as,Ordinary Shares,ORD,SK1120005071,BRATISLAVA STOCK EXCHANGE,1ZTS01NE,Unable to collect data for the field 'TR.COMPA...,Slovak Republic,Automobiles & Auto Parts,...,Unable to collect data for the field 'TR.Capit...,Unable to collect data for the field 'TR.CashF...,Unable to collect data for the field 'TR.CashF...,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
532,HAIr.AT,Haidemenos SA,Ordinary Shares,ORD,GRS350263000,ATHENS EXCHANGE S.A. CASH MARKET,HAIDE,EUR,Greece,Industrial & Commercial Services,...,-77500,-39320,-699500,0,"1,003700894","0,792661721","-0,038554623","-0,038554623",#DIV/0!,"0,990956648"
533,MLATV.EUA,A Toute Vitesse SA,Ordinary Shares,ORD,FR0010050773,NYSE EURONEXT - MARCHE LIBRE PARIS,MLATV,EUR,France,Transportation,...,NaN,NaN,NaN,"0,157308113","0,706426684","1,487015881","0,107985443","0,107985443","20,56245327","3,234640717"
534,REIB.EUB,Reibel SA,Ordinary Shares,ORD,BE0003829463,NYSE EURONEXT - MARCHE LIBRE BRUSSELS,REI,NaN,Belgium,Transportation,...,NaN,NaN,NaN,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
535,MLHPE.EUA,Hopening SA,Ordinary Shares,ORD,FR0010312181,NYSE EURONEXT - MARCHE LIBRE PARIS,MLHPE,EUR,France,Cyclical Consumer Services,...,NaN,NaN,NaN,"0,1574216","0,099345811","13,43097581","0,000816848","0,000816848","11,6306751","1,830919487"
536,CHRA.EUA,Imprimerie Chirat SA,Ordinary Shares,ORD,FR0000065773,NYSE EURONEXT - MARCHE LIBRE PARIS,MLIMP,EUR,France,Industrial & Commercial Services,...,NaN,NaN,NaN,"0,919310793","0,646298155","2,300271168","0,157472345","0,157472345","2,392318719","2,199284417"
537,MLGEL.EUA,D2l Groupe SA,Ordinary Shares,ORD,FR0012336675,NYSE EURONEXT - MARCHE LIBRE PARIS,MLGEL,Unable to collect data for the field 'TR.COMPA...,France,Industrial & Commercial Services,...,Unable to collect data for the field 'TR.Capit...,Unable to collect data for the field 'TR.CashF...,Unable to collect data for the field 'TR.CashF...,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
538,PROr.AT,Proodeftiki Technical Co SA,Ordinary Shares,ORD,GRS184003002,ATHENS EXCHANGE S.A. CASH MARKET,PRD,EUR,Greece,Industrial & Commercial Services,...,NaN,0,276880,"0,742647892","0,605777551","2,406037722","-0,029947199","-0,029947199",0,0
539,VTRr.AT,Bioter SA,Ordinary Shares,ORD,GRS135003002,ATHENS EXCHANGE S.A. CASH MARKET,BIOT,EUR,Greece,Industrial & Commercial Services,...,-17000,1241000,12556000,0,"-2,175886136","-2,258456711","-0,533814879","-0,533814879",#DIV/0!,"0,005485965"
540,MLV4S.EUA,Les Verandas 4 Saisons SA,Ordinary Shares,ORD,BE6201089735,NYSE EURONEXT - MARCHE LIBRE PARIS,MLV4S,NaN,Belgium,Cyclical Consumer Products,...,NaN,NaN,NaN,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
541,MLJSA.EUA,JSA Technology SA,Ordinary Shares,ORD,FR0010680033,NYSE EURONEXT - MARCHE LIBRE PARIS,MLJSA,NaN,France,Renewable Energy,...,NaN,NaN,NaN,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
542,MLKRI.EUA,Krief Group SA,Ordinary Shares,ORD,FR0004152700,NYSE EURONEXT - MARCHE LIBRE PARIS,MLKRI,NaN,France,Industrial & Commercial Services,...,NaN,NaN,NaN,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
543,1SES01AE.BV,Slovenske Energeticke Strojarne as,Ordinary Shares,ORD,SK1120008034,BRATISLAVA STOCK EXCHANGE,1SES01AE,EUR,Slovak Republic,Industrial Goods,...,-61000,2541000,5062000,"1,160404624","-0,068147247","-28,80078125","0,213682689","0,213682689","1,074752573","1,247147855"
544,LESr.AT,Maritime Company of Lesvos SA,Ordinary Shares,ORD,GRS243003019,ATHENS EXCHANGE S.A. CASH MARKET,NEL,EUR,Greece,Transportation,...,-7230,649130,1181350,"4,113031766","-1,128454118","-9,922083048","-3,259491636","-3,259491636","1,165266416","4,792777786"
545,LITF.EUL,Litho Formas SA,Ordinary Shares,ORD,PTLIT0AE0005,NYSE EURONEXT - EASYNEXT LISBON,LIT,EUR,Portugal,Industrial & Commercial Services,...,NaN,2770,-90640,"0,024471065","2,911877943","0,185978256","-0,089004112","-0,089004112","12,04578665","0,294773228"
546,CSSr.AT,Alpha Grissin Power and Environmental Control ...,Ordinary Shares,ORD,GRS480003003,ATHENS EXCHANGE S.A. CASH MARKET,AGRI,EUR,Greece,Software & IT Services,...,-32100,-36960,-624450,"0,002283448","-1,128915367","-3,273744712","-0,268891038","-0,268891038","594,8178408","1,358235834"
547,RER1R.RI,Rigas Elektromasinbuves Rupnica AS,Ordinary Shares,ORD,LV0000101012,NASDAQ OMX RIGA,RER1R,EUR,Latvia,Industrial Goods,...,-2043290,-1187660,-3980950,"0,279253132","2,425130488","0,544347861","0,045351043","0,045351043","9,068015378","2,532271695"
548,WOLFT.VI,Wolftank Adisa Holding AG,Ordinary Shares,ORD,AT0000A25NJ6,WIENER BOERSE AG DRITTER MARKT (THIRD MARKET),WOLF,Unable to collect data for the field 'TR.COMPA...,Austria,Industrial & Commercial Services,...,Unable to collect data for the field 'TR.Capit...,Unable to collect data for the field 'TR.CashF...,Unable to collect data for the field 'TR.CashF...,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
549,DESA.SCT,Desarrollos Especiales de Sistemas de Anclajes SA,Ordinary Shares,ORD,ES0126251018,BOLSA DE BARCELONA,DES,EUR,Spain,Industrial Goods,...,-1270330,-1073540,-830730,"0,185049376","0,552523925","2,02925994","0,040358368","0,040358368","9,936897486","1,838816684"
550,MLECO.EUA,Ecolutions GmbH & Co KGaA,Ordinary Shares,ORD,DE000A0XYM45,NYSE EURONEXT - MARCHE LIBRE PARIS,MLECO,EUR,Germany,Industrial & Commercial Services,...,NaN,NaN,NaN,0,"2,719228376","0,05816013","-0,041141691","-0,041141691",#DIV/0!,"0,181665051"
551,DPUY.EUA,Revival Expansion SA,Ordinary Shares,ORD,FR0000077232,NYSE EURONEXT - MARCHE LIBRE PARIS,MLGRD,EUR,France,Industrial & Commercial Services,...,NaN,NaN,NaN,"0,092113602","-18,46510737","-1,101081033","-0,06052969","-0,06052969","3,20208","0,294955122"

In [153]:
#pandas write data to excell file 
#write excel file 
excel_writer=pd.ExcelWriter("excel_file_path",engine='xlsxwriter')
data_frame.to_excel(excel_writer,"roe info")
excel_writer.save()

In [154]:
#sort datafra,e data by one column
Columns=data_frame.columns
print(data_frame.columns)
data=data_frame

Index(['code name ', 'Company Common Name', 'Instrument Type',
       'Asset Category Code', 'ISIN Code', 'Exchange Name', 'Ticker Symbol',
       'Currency Code', 'Country of Headquarters', 'TRBC Business Sector Name',
       'Return On Equity - Actual', 'Return On Assets - Actual',
       'Total Revenue', 'Normalized EBIT', 'Normalized EBITDA',
       'Net Income Incl Extra Before Distributions',
       'Depreciation And Amortization',
       'Selling/General/Administrative Expense, Total', 'Total Current Assets',
       'Total Liabilities', 'Total Current Liabilities', 'Total Equity',
       'Net Debt Incl. Pref.Stock & Min.Interest', 'Total Assets, Reported',
       'Total Long Term Debt', 'Cash', 'Cash and Equivalents', 'Quick Ratio',
       'Current Ratio', 'Accounts Payable', 'Total Inventory',
       'Common Stock, Total', 'Property/Plant/Equipment, Total - Net',
       'Cash from Operating Activities, Cumulative',
       'Capital Expenditures, Cumulative',
       'Cash from Investing Activities, Cumulative',
       'Cash from Financing Activities, Cumulative', 'debt to asset ratio ',
       'equity to asset ratio ', 'debt to equity ratio ',
       'Roa return on asset ', 'roe return on equity ',
       'long term coverage ratio', 'asset turnover rate '],
      dtype='object')

In [155]:
print(data_frame.values)

[['SIEGn.DE' 'Siemens AG' 'Ordinary Shares' ... '0,089952909'
  '3,062094395' '1,286387013']
 ['AIR.PA' 'Airbus SE' 'Ordinary Shares' ... '0,042371056' '4,064596102'
  '1,059222569']
 ['SCHN.PA' 'Schneider Electric SE' 'Ordinary Shares' ... '0,16072363'
  '4,379292035' '1,849667339']
 ...
 ['DESA.SCT' 'Desarrollos Especiales de Sistemas de Anclajes SA'
  'Ordinary Shares' ... '0,040358368' '9,936897486' '1,838816684']
 ['MLECO.EUA' 'Ecolutions GmbH & Co KGaA' 'Ordinary Shares' ...
  '-0,041141691' '#DIV/0!' '0,181665051']
 ['DPUY.EUA' 'Revival Expansion SA' 'Ordinary Shares' ... '-0,06052969'
  '3,20208' '0,294955122']]

In [156]:
csvfile=data_frame

In [157]:
import csv 
from collections import defaultdict 
columns=defaultdict(list)
print(data_frame)

      code name                                 Company Common Name  \
0       SIEGn.DE                                         Siemens AG
1         AIR.PA                                          Airbus SE
2        SCHN.PA                              Schneider Electric SE
3        SGEF.PA                                           Vinci SA
4         SAF.PA                                          Safran SA
5       DPWGn.DE                                   Deutsche Post AG
6        SGOB.PA                       Compagnie de Saint Gobain SA
7        LHAG.DE                              Deutsche Lufthansa AG
8        BOUY.PA                                        Bouygues SA
9       MTXGn.DE                                MTU Aero Engines AG
10       TCFP.PA                                          Thales SA
11      WLSNc.AS                                  Wolters Kluwer NV
12       LEGD.PA                                         Legrand SA
13        FER.MC                                       Ferrovial SA
14      TEPRF.PA                                 Teleperformance SE
15       AIRF.PA                                  Air France KLM SA
16       ALSO.PA                                          Alstom SA
17      SGREN.MC                 Siemens Gamesa Renewable Energy SA
18      LIGHT.AS                                         Signify NV
19        ACS.MC     ACS Actividades de Construccion y Servicios SA
20       RAND.AS                                        Randstad NV
21       RHMG.DE                                     Rheinmetall AG
22       FOUG.PA                                         Eiffage SA
23       IMCD.AS                                            IMCD NV
24       GETP.PA                                         Getlink SE
25       AENA.MC                                        Aena SME SA
26      BNRGn.DE                                        Brenntag AG
27       EDEN.PA                                         Edenred SA
28       BICP.PA                                     Societe BIC SA
29       OSRn.DE                                     Osram Licht AG
..           ...                                                ...
522     RKB1R.RI                             Rigas Kugu Buvetava AS
523      DKRr.AT                                   Domiki Kritis SA
524      VOGr.AT                            Vogiatzoglou Systems SA
525      XYLr.AT                         Interwood Xylemporia ATENE
526    MLVAL.EUA                                       Valoneo SASU
527      CETG.LJ                                           Cetis dd
528     URBA.SCT                                Urbar Ingenieros SA
529      GCEr.AT                                           AEGEK SA
530     PWBP.EUA                                       Phone Web SA
531  1ZTS01NE.BV                                     ZTS Sabinov as
532      HAIr.AT                                      Haidemenos SA
533    MLATV.EUA                                 A Toute Vitesse SA
534     REIB.EUB                                          Reibel SA
535    MLHPE.EUA                                        Hopening SA
536     CHRA.EUA                               Imprimerie Chirat SA
537    MLGEL.EUA                                      D2l Groupe SA
538      PROr.AT                        Proodeftiki Technical Co SA
539      VTRr.AT                                          Bioter SA
540    MLV4S.EUA                          Les Verandas 4 Saisons SA
541    MLJSA.EUA                                  JSA Technology SA
542    MLKRI.EUA                                     Krief Group SA
543  1SES01AE.BV                 Slovenske Energeticke Strojarne as
544      LESr.AT                      Maritime Company of Lesvos SA
545     LITF.EUL                                    Litho Formas SA
546      CSSr.AT  Alpha Grissin Power and Environmental Control ...
547     RER1R.RI                 Rigas Elektromasinbuves Rupnica AS
548     WOLFT.VI                          Wolftank Adisa Holding AG
549     DESA.SCT  Desarrollos Especiales de Sistemas de Anclajes SA
550    MLECO.EUA                          Ecolutions GmbH & Co KGaA
551     DPUY.EUA                               Revival Expansion SA

     Instrument Type Asset Category Code     ISIN Code  \
0    Ordinary Shares                 ORD  DE0007236101
1    Ordinary Shares                 ORD  NL0000235190
2    Ordinary Shares                 ORD  FR0000121972
3    Ordinary Shares                 ORD  FR0000125486
4    Ordinary Shares                 ORD  FR0000073272
5    Ordinary Shares                 ORD  DE0005552004
6    Ordinary Shares                 ORD  FR0000125007
7    Ordinary Shares                 ORD  DE0008232125
8    Ordinary Shares                 ORD  FR0000120503
9    Ordinary Shares                 ORD  DE000A0D9PT0
10   Ordinary Shares                 ORD  FR0000121329
11   Ordinary Shares                 ORD  NL0000395903
12   Ordinary Shares                 ORD  FR0010307819
13   Ordinary Shares                 ORD  ES0118900010
14   Ordinary Shares                 ORD  FR0000051807
15   Ordinary Shares                 ORD  FR0000031122
16   Ordinary Shares                 ORD  FR0010220475
17   Ordinary Shares                 ORD  ES0143416115
18   Ordinary Shares                 ORD  NL0011821392
19   Ordinary Shares                 ORD  ES0167050915
20   Ordinary Shares                 ORD  NL0000379121
21   Ordinary Shares                 ORD  DE0007030009
22   Ordinary Shares                 ORD  FR0000130452
23   Ordinary Shares                 ORD  NL0010801007
24   Ordinary Shares                 ORD  FR0010533075
25   Ordinary Shares                 ORD  ES0105046009
26   Ordinary Shares                 ORD  DE000A1DAHH0
27   Ordinary Shares                 ORD  FR0010908533
28   Ordinary Shares                 ORD  FR0000120966
29   Ordinary Shares                 ORD  DE000LED4000
..               ...                 ...           ...
522  Ordinary Shares                 ORD  LV0000100378
523  Ordinary Shares                 ORD  GRS364253005
524  Ordinary Shares                 ORD  GRS407183003
525  Ordinary Shares                 ORD  GRS131003006
526  Ordinary Shares                 ORD  FR0012833770
527  Ordinary Shares                 ORD  SI0031100843
528  Ordinary Shares                 ORD  ES0182484214
529  Ordinary Shares                 ORD  GRS182003004
530  Ordinary Shares                 ORD  FR0000185480
531  Ordinary Shares                 ORD  SK1120005071
532  Ordinary Shares                 ORD  GRS350263000
533  Ordinary Shares                 ORD  FR0010050773
534  Ordinary Shares                 ORD  BE0003829463
535  Ordinary Shares                 ORD  FR0010312181
536  Ordinary Shares                 ORD  FR0000065773
537  Ordinary Shares                 ORD  FR0012336675
538  Ordinary Shares                 ORD  GRS184003002
539  Ordinary Shares                 ORD  GRS135003002
540  Ordinary Shares                 ORD  BE6201089735
541  Ordinary Shares                 ORD  FR0010680033
542  Ordinary Shares                 ORD  FR0004152700
543  Ordinary Shares                 ORD  SK1120008034
544  Ordinary Shares                 ORD  GRS243003019
545  Ordinary Shares                 ORD  PTLIT0AE0005
546  Ordinary Shares                 ORD  GRS480003003
547  Ordinary Shares                 ORD  LV0000101012
548  Ordinary Shares                 ORD  AT0000A25NJ6
549  Ordinary Shares                 ORD  ES0126251018
550  Ordinary Shares                 ORD  DE000A0XYM45
551  Ordinary Shares                 ORD  FR0000077232

                                     Exchange Name Ticker Symbol  \
0                                            XETRA           SIE
1                   NYSE EURONEXT - EURONEXT PARIS           AIR
2                   NYSE EURONEXT - EURONEXT PARIS            SU
3                   NYSE EURONEXT - EURONEXT PARIS            DG
4                   NYSE EURONEXT - EURONEXT PARIS           SAF
5                                            XETRA           DPW
6                   NYSE EURONEXT - EURONEXT PARIS           SGO
7                                            XETRA           LHA
8                   NYSE EURONEXT - EURONEXT PARIS            EN
9                                            XETRA           MTX
10                  NYSE EURONEXT - EURONEXT PARIS            HO
11              NYSE EURONEXT - EURONEXT AMSTERDAM           WKL
12                  NYSE EURONEXT - EURONEXT PARIS            LR
13                                 BOLSA DE MADRID           FER
14                  NYSE EURONEXT - EURONEXT PARIS           TEP
15                  NYSE EURONEXT - EURONEXT PARIS            AF
16                  NYSE EURONEXT - EURONEXT PARIS           ALO
17                                 BOLSA DE MADRID          SGRE
18              NYSE EURONEXT - EURONEXT AMSTERDAM         LIGHT
19                                 BOLSA DE MADRID           ACS
20              NYSE EURONEXT - EURONEXT AMSTERDAM          RAND
21                                           XETRA           RHM
22                  NYSE EURONEXT - EURONEXT PARIS           FGR
23              NYSE EURONEXT - EURONEXT AMSTERDAM          IMCD
24                  NYSE EURONEXT - EURONEXT PARIS           GET
25                                 BOLSA DE MADRID          AENA
26                                           XETRA           BNR
27                  NYSE EURONEXT - EURONEXT PARIS          EDEN
28                  NYSE EURONEXT - EURONEXT PARIS            BB
29                                           XETRA           OSR
..                                             ...           ...
522                                NASDAQ OMX RIGA         RKB1R
523               ATHENS EXCHANGE S.A. CASH MARKET         DOMIK
524               ATHENS EXCHANGE S.A. CASH MARKET         VOSYS
525               ATHENS EXCHANGE S.A. CASH MARKET         XYLEK
526             NYSE EURONEXT - MARCHE LIBRE PARIS         MLVAL
527     LJUBLJANA STOCK EXCHANGE (OFFICIAL MARKET)          CETG
528                                BOLSA DE MADRID           UIN
529               ATHENS EXCHANGE S.A. CASH MARKET         AEGEK
530             NYSE EURONEXT - MARCHE LIBRE PARIS         MLPHW
531                      BRATISLAVA STOCK EXCHANGE      1ZTS01NE
532               ATHENS EXCHANGE S.A. CASH MARKET         HAIDE
533             NYSE EURONEXT - MARCHE LIBRE PARIS         MLATV
534          NYSE EURONEXT - MARCHE LIBRE BRUSSELS           REI
535             NYSE EURONEXT - MARCHE LIBRE PARIS         MLHPE
536             NYSE EURONEXT - MARCHE LIBRE PARIS         MLIMP
537             NYSE EURONEXT - MARCHE LIBRE PARIS         MLGEL
538               ATHENS EXCHANGE S.A. CASH MARKET           PRD
539               ATHENS EXCHANGE S.A. CASH MARKET          BIOT
540             NYSE EURONEXT - MARCHE LIBRE PARIS         MLV4S
541             NYSE EURONEXT - MARCHE LIBRE PARIS         MLJSA
542             NYSE EURONEXT - MARCHE LIBRE PARIS         MLKRI
543                      BRATISLAVA STOCK EXCHANGE      1SES01AE
544               ATHENS EXCHANGE S.A. CASH MARKET           NEL
545                NYSE EURONEXT - EASYNEXT LISBON           LIT
546               ATHENS EXCHANGE S.A. CASH MARKET          AGRI
547                                NASDAQ OMX RIGA         RER1R
548  WIENER BOERSE AG DRITTER MARKT (THIRD MARKET)          WOLF
549                             BOLSA DE BARCELONA           DES
550             NYSE EURONEXT - MARCHE LIBRE PARIS         MLECO
551             NYSE EURONEXT - MARCHE LIBRE PARIS         MLGRD

                                         Currency Code  \
0                                                  EUR
1                                                  EUR
2                                                  EUR
3                                                  EUR
4                                                  EUR
5                                                  EUR
6                                                  EUR
7                                                  EUR
8                                                  EUR
9                                                  EUR
10                                                 EUR
11                                                 EUR
12                                                 EUR
13                                                 EUR
14                                                 EUR
15                                                 EUR
16                                                 EUR
17                                                 EUR
18                                                 EUR
19                                                 EUR
20                                                 EUR
21                                                 EUR
22                                                 EUR
23                                                 EUR
24                                                 EUR
25                                                 EUR
26                                                 EUR
27                                                 EUR
28                                                 EUR
29                                                 EUR
..                                                 ...
522                                                EUR
523                                                EUR
524                                                EUR
525                                                EUR
526  Unable to collect data for the field 'TR.COMPA...
527                                                EUR
528                                                EUR
529                                                EUR
530                                                EUR
531  Unable to collect data for the field 'TR.COMPA...
532                                                EUR
533                                                EUR
534                                                NaN
535                                                EUR
536                                                EUR
537  Unable to collect data for the field 'TR.COMPA...
538                                                EUR
539                                                EUR
540                                                NaN
541                                                NaN
542                                                NaN
543                                                EUR
544                                                EUR
545                                                EUR
546                                                EUR
547                                                EUR
548  Unable to collect data for the field 'TR.COMPA...
549                                                EUR
550                                                EUR
551                                                EUR

    Country of Headquarters         TRBC Business Sector Name  ...  \
0                   Germany          Industrial Conglomerates  ...
1               Netherlands                  Industrial Goods  ...
2                    France                  Industrial Goods  ...
3                    France  Industrial & Commercial Services  ...
4                    France                  Industrial Goods  ...
5                   Germany                    Transportation  ...
6                    France        Cyclical Consumer Products  ...
7                   Germany                    Transportation  ...
8                    France  Industrial & Commercial Services  ...
9                   Germany                  Industrial Goods  ...
10                   France                  Industrial Goods  ...
11              Netherlands  Industrial & Commercial Services  ...
12                   France                  Industrial Goods  ...
13                    Spain  Industrial & Commercial Services  ...
14                   France  Industrial & Commercial Services  ...
15                   France                    Transportation  ...
16                   France                  Industrial Goods  ...
17                    Spain                  Renewable Energy  ...
18              Netherlands        Cyclical Consumer Products  ...
19                    Spain  Industrial & Commercial Services  ...
20              Netherlands  Industrial & Commercial Services  ...
21                  Germany          Automobiles & Auto Parts  ...
22                   France  Industrial & Commercial Services  ...
23              Netherlands                         Chemicals  ...
24                   France                    Transportation  ...
25                    Spain                    Transportation  ...
26                  Germany                         Chemicals  ...
27                   France  Industrial & Commercial Services  ...
28                   France  Industrial & Commercial Services  ...
29                  Germany                  Industrial Goods  ...
..                      ...                               ...  ...
522                  Latvia                  Industrial Goods  ...
523                  Greece  Industrial & Commercial Services  ...
524                  Greece        Cyclical Consumer Products  ...
525                  Greece                 Applied Resources  ...
526                  France  Industrial & Commercial Services  ...
527                Slovenia  Industrial & Commercial Services  ...
528                   Spain                 Mineral Resources  ...
529                  Greece  Industrial & Commercial Services  ...
530                  France        Cyclical Consumer Services  ...
531         Slovak Republic          Automobiles & Auto Parts  ...
532                  Greece  Industrial & Commercial Services  ...
533                  France                    Transportation  ...
534                 Belgium                    Transportation  ...
535                  France        Cyclical Consumer Services  ...
536                  France  Industrial & Commercial Services  ...
537                  France  Industrial & Commercial Services  ...
538                  Greece  Industrial & Commercial Services  ...
539                  Greece  Industrial & Commercial Services  ...
540                 Belgium        Cyclical Consumer Products  ...
541                  France                  Renewable Energy  ...
542                  France  Industrial & Commercial Services  ...
543         Slovak Republic                  Industrial Goods  ...
544                  Greece                    Transportation  ...
545                Portugal  Industrial & Commercial Services  ...
546                  Greece            Software & IT Services  ...
547                  Latvia                  Industrial Goods  ...
548                 Austria  Industrial & Commercial Services  ...
549                   Spain                  Industrial Goods  ...
550                 Germany  Industrial & Commercial Services  ...
551                  France  Industrial & Commercial Services  ...

                      Capital Expenditures, Cumulative  \
0                                          -2602000000
1                                          -2558000000
2                                           -749000000
3                                          -1920000000
4                                          -1089000000
5                                          -2203000000
6                                          -1722000000
7                                          -3338000000
8                                          -1931000000
9                                           -305000000
10                                          -438900000
11                                          -210000000

In [158]:
print(data_frame.head())

  code name     Company Common Name  Instrument Type Asset Category Code  \
0   SIEGn.DE             Siemens AG  Ordinary Shares                 ORD
1     AIR.PA              Airbus SE  Ordinary Shares                 ORD
2    SCHN.PA  Schneider Electric SE  Ordinary Shares                 ORD
3    SGEF.PA               Vinci SA  Ordinary Shares                 ORD
4     SAF.PA              Safran SA  Ordinary Shares                 ORD

      ISIN Code                   Exchange Name Ticker Symbol Currency Code  \
0  DE0007236101                           XETRA           SIE           EUR
1  NL0000235190  NYSE EURONEXT - EURONEXT PARIS           AIR           EUR
2  FR0000121972  NYSE EURONEXT - EURONEXT PARIS            SU           EUR
3  FR0000125486  NYSE EURONEXT - EURONEXT PARIS            DG           EUR
4  FR0000073272  NYSE EURONEXT - EURONEXT PARIS           SAF           EUR

  Country of Headquarters         TRBC Business Sector Name  ...  \
0                 Germany          Industrial Conglomerates  ...
1             Netherlands                  Industrial Goods  ...
2                  France                  Industrial Goods  ...
3                  France  Industrial & Commercial Services  ...
4                  France                  Industrial Goods  ...

  Capital Expenditures, Cumulative Cash from Investing Activities, Cumulative  \
0                      -2602000000                                -3774000000
1                      -2558000000                                -2530000000
2                       -749000000                                -1238000000
3                      -1920000000                                -3046000000
4                      -1089000000                                 -334000000

  Cash from Financing Activities, Cumulative debt to asset ratio   \
0                                -1946000000          0,420100378
1                                  321000000          0,260597251
2                                -1522000000          0,422366749
3                                -1200000000          0,633353631
4                                  393000000          0,203770965

  equity to asset ratio  debt to equity ratio  Roa return on asset   \
0            0,704396183           2,054889715          0,089952909
1            0,192742543           9,190782123          0,042371056
2            1,479928235            1,01288074           0,16072363
3            0,677842898           2,919094941          0,104582128
4            0,499252217           2,464748048          0,243029591

  roe return on equity  long term coverage ratio asset turnover rate
0           0,089952909              3,062094395          1,286387013
1           0,042371056              4,064596102          1,059222569
2            0,16072363              4,379292035          1,849667339
3           0,104582128              2,456195169          1,555640128
4           0,243029591              4,292529489          0,874692875

[5 rows x 44 columns]

In [159]:

data_frame.head(500)

,code name,Company Common Name,Instrument Type,Asset Category Code,ISIN Code,Exchange Name,Ticker Symbol,Currency Code,Country of Headquarters,TRBC Business Sector Name,...,"Capital Expenditures, Cumulative","Cash from Investing Activities, Cumulative","Cash from Financing Activities, Cumulative",debt to asset ratio,equity to asset ratio,debt to equity ratio,Roa return on asset,roe return on equity,long term coverage ratio,asset turnover rate
0,SIEGn.DE,Siemens AG,Ordinary Shares,ORD,DE0007236101,XETRA,SIE,EUR,Germany,Industrial Conglomerates,...,-2602000000,-3774000000,-1946000000,"0,420100378","0,704396183","2,054889715","0,089952909","0,089952909","3,062094395","1,286387013"
1,AIR.PA,Airbus SE,Ordinary Shares,ORD,NL0000235190,NYSE EURONEXT - EURONEXT PARIS,AIR,EUR,Netherlands,Industrial Goods,...,-2558000000,-2530000000,321000000,"0,260597251","0,192742543","9,190782123","0,042371056","0,042371056","4,064596102","1,059222569"
2,SCHN.PA,Schneider Electric SE,Ordinary Shares,ORD,FR0000121972,NYSE EURONEXT - EURONEXT PARIS,SU,EUR,France,Industrial Goods,...,-749000000,-1238000000,-1522000000,"0,422366749","1,479928235","1,01288074","0,16072363","0,16072363","4,379292035","1,849667339"
3,SGEF.PA,Vinci SA,Ordinary Shares,ORD,FR0000125486,NYSE EURONEXT - EURONEXT PARIS,DG,EUR,France,Industrial & Commercial Services,...,-1920000000,-3046000000,-1200000000,"0,633353631","0,677842898","2,919094941","0,104582128","0,104582128","2,456195169","1,555640128"
4,SAF.PA,Safran SA,Ordinary Shares,ORD,FR0000073272,NYSE EURONEXT - EURONEXT PARIS,SAF,EUR,France,Industrial Goods,...,-1089000000,-334000000,393000000,"0,203770965","0,499252217","2,464748048","0,243029591","0,243029591","4,292529489","0,874692875"
5,DPWGn.DE,Deutsche Post AG,Ordinary Shares,ORD,DE0005552004,XETRA,DPW,EUR,Germany,Transportation,...,-2203000000,-2091000000,-1087000000,"0,34846842","0,856397398","2,060219989","0,183857414","0,183857414","11,75495916","4,096232041"
6,SGOB.PA,Compagnie de Saint Gobain SA,Ordinary Shares,ORD,FR0000125007,NYSE EURONEXT - EURONEXT PARIS,SGO,EUR,France,Cyclical Consumer Products,...,-1722000000,-2033000000,-1117000000,"0,622398105","1,135859404","1,506693734","0,097594416","0,097594416","4,086312206","2,543312975"
7,LHAG.DE,Deutsche Lufthansa AG,Ordinary Shares,ORD,DE0008232125,XETRA,LHA,EUR,Germany,Transportation,...,-3338000000,-5006000000,-245000000,"0,556895457","0,816665155","2,97224381","0,212167921","0,212167921","5,792738522","3,225949769"
8,BOUY.PA,Bouygues SA,Ordinary Shares,ORD,FR0000120503,NYSE EURONEXT - EURONEXT PARIS,EN,EUR,France,Industrial & Commercial Services,...,-1931000000,-1481000000,-362000000,"0,309728834","0,483393058","3,016707236","0,057870247","0,057870247","5,685201174","1,760870728"
9,MTXGn.DE,MTU Aero Engines AG,Ordinary Shares,ORD,DE000A0D9PT0,XETRA,MTX,EUR,Germany,Industrial Goods,...,-305000000,-340800000,-332900000,"0,331296117","0,672654096","2,448864266","0,132332116","0,132332116","4,384026997","1,45241112"
10,TCFP.PA,Thales SA,Ordinary Shares,ORD,FR0000121329,NYSE EURONEXT - EURONEXT PARIS,HO,EUR,France,Industrial Goods,...,-438900000,-607700000,-381200000,"0,064297949","0,331888006","3,764552898","0,045841369","0,045841369","15,97011012","1,026845321"
11,WLSNc.AS,Wolters Kluwer NV,Ordinary Shares,ORD,NL0000395903,NYSE EURONEXT - EURONEXT AMSTERDAM,WKL,EUR,Netherlands,Industrial & Commercial Services,...,-210000000,-409000000,-60000000,"0,765613243","0,838224229","2,80475763","0,239277652","0,239277652","2,146437346","1,643340858"
12,LEGD.PA,Legrand SA,Ordinary Shares,ORD,FR0010307819,NYSE EURONEXT - EURONEXT PARIS,LR,EUR,France,Industrial Goods,...,-144600000,-1802100000,887400000,"1,017747581","1,704179535","1,277171024","0,292855672","0,292855672","2,233694773","2,273337451"
13,FER.MC,Ferrovial SA,Ordinary Shares,ORD,ES0118900010,BOLSA DE MADRID,FER,EUR,Spain,Industrial & Commercial Services,...,-135000000,-468000000,324000000,"0,931663153","0,68250031","3,177721243","0,056182562","0,056182562","0,685835996","0,638968126"
14,TEPRF.PA,Teleperformance SE,Ordinary Shares,ORD,FR0000051807,NYSE EURONEXT - EURONEXT PARIS,TEP,EUR,France,Industrial & Commercial Services,...,-148000000,-151000000,-453000000,"1,009461426","1,390101892","1,35078534","0,227074236","0,227074236","3,01369863","3,042212518"
15,AIRF.PA,Air France KLM SA,Ordinary Shares,ORD,FR0000031122,NYSE EURONEXT - EURONEXT PARIS,AF,EUR,France,Transportation,...,-2552000000,-2692000000,-640000000,"1,088430117","0,265842349","11,44310631","0,017995142","0,017995142","2,623694087","2,855707662"
16,ALSO.PA,Alstom SA,Ordinary Shares,ORD,FR0010220475,NYSE EURONEXT - EURONEXT PARIS,ALO,EUR,France,Industrial Goods,...,-293000000,-353000000,-305000000,"0,166499785","0,482906594","2,923578199","0,052209984","0,052209984","6,310996564","1,050779574"
17,SGREN.MC,Siemens Gamesa Renewable Energy SA,Ordinary Shares,ORD,ES0143416115,BOLSA DE MADRID,SGRE,EUR,Spain,Renewable Energy,...,-415076000,-417252000,501758000,"0,112079532","0,806754732","1,725860905","0,009531935","0,009531935","11,08417011","1,242308593"
18,LIGHT.AS,Signify NV,Ordinary Shares,ORD,NL0011821392,NYSE EURONEXT - EURONEXT AMSTERDAM,LIGHT,EUR,Netherlands,Cyclical Consumer Products,...,-96000000,-26000000,-484000000,"0,346975089","0,664887307","1,978590544","0,086892052","0,086892052","5,952991453","2,065539739"
19,ACS.MC,ACS Actividades de Construccion y Servicios SA,Ordinary Shares,ORD,ES0167050915,BOLSA DE MADRID,ACS,EUR,Spain,Industrial & Commercial Services,...,-635744000,-301882000,-477948000,"0,250107324","0,181395346","7,373091042","0,0388687","0,0388687","6,762340207","1,691310812"
20,RAND.AS,Randstad NV,Ordinary Shares,ORD,NL0000379121,NYSE EURONEXT - EURONEXT AMSTERDAM,RAND,EUR,Netherlands,Industrial & Commercial Services,...,-107300000,-457400000,-557200000,"0,12574968","0,835906007","1,296612562","0,124156917","0,124156917","36,39218139","4,576305181"
21,RHMG.DE,Rheinmetall AG,Ordinary Shares,ORD,DE0007030009,XETRA,RHM,EUR,Germany,Automobiles & Auto Parts,...,-270000000,-189000000,-200000000,"0,164651698","0,528497409","2,369281046","0,064478987","0,064478987","10,30769231","1,697179044"
22,FOUG.PA,Eiffage SA,Ordinary Shares,ORD,FR0000130452,NYSE EURONEXT - EURONEXT PARIS,FGR,EUR,France,Industrial & Commercial Services,...,-595000000,-598000000,-663000000,"1,032282794","0,365417376","5,999067599","0,046678024","0,046678024","1,268091427","1,309028961"
23,IMCD.AS,IMCD NV,Ordinary Shares,ORD,NL0010801007,NYSE EURONEXT - EURONEXT AMSTERDAM,IMCD,EUR,Netherlands,Chemicals,...,-12814000,-181380000,95977000,"0,552039859","1,106633906","1,268628777","0,117255865","0,117255865","5,243599295","2,894675817"
24,GETP.PA,Getlink SE,Ordinary Shares,ORD,FR0010533075,NYSE EURONEXT - EURONEXT PARIS,GET,EUR,France,Transportation,...,-275240000,-277109000,16002000,"5,482904289","2,665109105","2,652707541","0,146745168","0,146745168","0,244808898","1,342263757"
25,AENA.MC,Aena SME SA,Ordinary Shares,ORD,ES0105046009,BOLSA DE MADRID,AENA,EUR,Spain,Transportation,...,-370409000,-361614000,-1364274000,"5,99422822","4,681384733","1,693814169","1,014967413","1,014967413","0,544333877","3,262861488"
26,BNRGn.DE,Brenntag AG,Ordinary Shares,ORD,DE000A1DAHH0,XETRA,BNR,EUR,Germany,Chemicals,...,-151400000,-244900000,-224300000,"0,430860966","0,864805119","1,450154715","0,104944735","0,104944735","7,927698643","3,415735893"
27,EDEN.PA,Edenred SA,Ordinary Shares,ORD,FR0010908533,NYSE EURONEXT - EURONEXT PARIS,EDEN,EUR,France,Industrial & Commercial Services,...,-78000000,-176000000,-264000000,"0,384513858","-0,33150022","-5,121433311","0,053013638","0,053013638","0,755148741","0,290365156"
28,BICP.PA,Societe BIC SA,Ordinary Shares,ORD,FR0000120966,NYSE EURONEXT - EURONEXT PARIS,BB,EUR,France,Industrial & Commercial Services,...,-174811000,-111761000,-275358000,"0,000181478","1,436775933","0,382783153","0,242541033","0,242541033","9494,92093","1,723121595"
29,OSRn.DE,Osram Licht AG,Ordinary Shares,ORD,DE000LED4000,XETRA,OSR,EUR,Germany,Industrial Goods,...,-467000000,-625000000,72000000,"0,076612903","1,278225806","0,865141956","0,069052419","0,069052419","27,07236842","2,074092742"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,VILr.AT,Unibios Holdings SA,Ordinary Shares,ORD,GRS084003011,ATHENS EXCHANGE S.A. CASH MARKET,BIOSK,EUR,Greece,Industrial Goods,...,-1101630,-1522890,1254970,"0,636041287","1,719214734","1,285151578","-0,076437968","-0,076437968","1,712312421","1,089101396"
471,SMPV.VI,Semperit AG Holding,Ordinary Shares,ORD,AT0000785555,WIENER BOERSE AG AMTLICHER HANDEL (OFFICIAL MA...,SEM,EUR,Austria,Automobiles & Auto Parts,...,-74475000,70520000,-154899000,"0,673020615","0,613596656","2,063531845","-0,056526787","-0,056526787","2,861682347","1,925971213"
472,EKTr.AT,Ekter SA,Ordinary Shares,ORD,GRS222213001,ATHENS EXCHANGE S.A. CASH MARKET,EKTER,EUR,Greece,Industrial & Commercial Services,...,-16560,-369760,-441310,0,"1,550850337","0,245743619","-0,106698221","-0,106698221",#DIV/0!,"0,669008382"
473,INRr.AT,Intracom Holdings SA,Ordinary Shares,ORD,GRS087003000,ATHENS EXCHANGE S.A. CASH MARKET,INTRK,EUR,Greece,Investment Holding Companies,...,-14789000,-49446000,53853000,"0,231151449","0,556907762","2,069511399","0,002004854","0,002004854","3,719690158","0,859811769"
474,TAL1T.TL,Tallink Grupp AS,Ordinary Shares,ORD,EE3100004466,NASDAQ OMX TALLINN,TAL1T,EUR,Estonia,Cyclical Consumer Services,...,-219207000,-86758000,-39282000,"2,209348328","4,607927841","0,863728493","0,256194659","0,256194659","2,411606412","5,328078595"
475,RBAV.VI,Rosenbauer International AG,Ordinary Shares,ORD,AT0000922554,WIENER BOERSE AG AMTLICHER HANDEL (OFFICIAL MA...,ROS,EUR,Austria,Industrial Goods,...,-22187100,-21950800,-15689600,"0,226240301","0,471946328","2,003631594","0,017067329","0,017067329","8,491749132","1,921175881"
476,DQ5.I,CPL Resources PLC,Ordinary Shares,ORD,IE0007214426,IRISH STOCK EXCHANGE - ALL MARKET,DQ5,EUR,Ireland; Republic of,Industrial & Commercial Services,...,-1244000,-1244000,-28692000,0,"0,689849357","0,764404651","0,120163115","0,120163115",#DIV/0!,"3,903796315"
477,LKPG.LJ,Luka Koper dd,Ordinary Shares,ORD,SI0031101346,LJUBLJANA STOCK EXCHANGE (OFFICIAL MARKET),LKPG,EUR,Slovenia,Transportation,...,-32689090,-30002300,-12698740,"1,308020095","4,550230776","0,531723832","0,454204804","0,454204804","2,10005575","2,746915121"
478,DROr.AT,Dromeas Office Furniture Industry SA,Ordinary Shares,ORD,GRS412503005,ATHENS EXCHANGE S.A. CASH MARKET,DROME,EUR,Greece,Industrial & Commercial Services,...,-262000,-261000,-558000,"0,866872884","1,080496595","1,418025221","-0,037254273","-0,037254273","0,528298059","0,457967262"
479,HAE1T.TL,Harju Elekter AS,Ordinary Shares,ORD,EE3100004250,NASDAQ OMX TALLINN,HAE1T,EUR,Estonia,Industrial Goods,...,-3265000,6284000,-3126000,"0,059737647","1,434360438","0,28774044","0,597971794","0,597971794","35,18969072","2,102149324"
480,EPAr.AT,Attica Holdings SA,Ordinary Shares,ORD,GRS144003001,ATHENS EXCHANGE S.A. CASH MARKET,ATTICA,EUR,Greece,Transportation,...,-1185000,-7113000,-25637000,"1,571030845","2,951974504","0,6860926","0,0091362","0,0091362","1,266338665","1,989457103"
481,INCr.AT,Intracom Constructions Technical and Steel Con...,Ordinary Shares,ORD,GRS432003028,ATHENS EXCHANGE S.A. CASH MARKET,INKAT,EUR,Greece,Industrial & Commercial Services,...,-11824790,-19250590,18512660,"0,359262969","0,300078599","4,830375054","-0,042440852","-0,042440852","2,182556101","0,784111584"
482,MRK1T.TL,Merko Ehitus AS,Ordinary Shares,ORD,EE3100098328,NASDAQ OMX TALLINN,MRK1T,EUR,Estonia,Industrial & Commercial Services,...,-1367000,991000,6089000,"0,150183573","0,556360512","1,128716294","0,062803729","0,062803729","9,0385907","1,357447845"
483,MLITN.EUA,Italy Innovazioni SpA,Ordinary Shares,ORD,IT0005336521,NYSE EURONEXT - MARCHE LIBRE PARIS,MLITN,Unable to collect data for the field 'TR.COMPA...,Italy,Industrial Goods,...,Unable to collect data for the field 'TR.Capit...,Unable to collect data for the field 'TR.CashF...,Unable to collect data for the field 'TR.CashF...,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
484,OLTr.AT,Thessaloniki Port Authority SA,Ordinary Shares,ORD,GRS427003009,ATHENS EXCHANGE S.A. CASH MARKET,OLTH,EUR,Greece,Transportation,...,-2397150,16769750,-4939200,0,"1,372043483","0,126447735","0,072089575","0,072089575",#DIV/0!,"0,539773451"
485,SWUT.VI,SW Umwelttechnik Stoiser & Wolschner AG,Ordinary Shares,ORD,AT0000808209,WIENER BOERSE AG AMTLICHER HANDEL (OFFICIAL MA...,SWUT,EUR,Austria,Industrial & Commercial Services,...,-2930000,-396000,-3775000,"2,167056123","0,181732464","17,15700429","0,044438978","0,044438978","1,159285674","2,512237117"
486,ELNr.AT,Elton SA,Ordinary Shares,ORD,GRS397003005,ATHENS EXCHANGE S.A. CASH MARKET,ELTON,EUR,Greece,Chemicals,...,-1708030,-1684220,718680,"0,075480328","0,678824496","0,891415267","0,045056489","0,045056489","22,80114003","1,721037521"
487,LYKr.AT,Inform P Lykos SA,Ordinary Shares,ORD,GRS208303008,ATHENS EXCHANGE S.A. CASH MARKET,LYK,EUR,Greece,Industrial & Commercial Services,...,-1435720,-1387450,-845670,"0,189644416","2,124763775","0,750521099","-0,02933714","-0,02933714","14,89724209","2,82517877"
488,CDUL.EUL,Conduril Engenharia SA,Ordinary Shares,ORD,PTCDU0AE0003,NYSE EURONEXT - EASYNEXT LISBON,CDU,EUR,Portugal,Industrial & Commercial Services,...,-8778800,-1598550,-25428460,"0,170291958","0,729507401","1,093465347","0,023465392","0,023465392","2,762331584","0,470402853"
489,ELTr.AT,Eltrak SA,Ordinary Shares,ORD,GRS142003003,ATHENS EXCHANGE S.A. CASH MARKET,ELTRK,EUR,Greece,Industrial Goods,...,-527000,-279000,-9971000,"0,013811798","1,146508326","1,072055843","0,106213158","0,106213158","145,2975078","2,006819844"
490,CLEN.VI,Cleen Energy AG,Ordinary Shares,ORD,AT0000A1PY49,WIENER BOERSE AG AMTLICHER HANDEL (OFFICIAL MA...,CLEN,EUR,Austria,Industrial Goods,...,-19380,-11210,309060,0,"1,833770139","0,971598091","-1,893882282","-1,893882282",#DIV/0!,"2,675162628"
491,MTPT.MT,MaltaPost plc,Ordinary Shares,ORD,MT0000390105,MALTA STOCK EXCHANGE,MTP,EUR,Malta,Transportation,...,-1545000,-1443000,-244000,0,"1,032404577","0,756006768","0,087911608","0,087911608",#DIV/0!,"1,678661892"
492,WTE.VI,NET New Energy Technologies AG,Ordinary Shares,ORD,ATNEWENERGY6,WIENER BOERSE AG DRITTER MARKT (THIRD MARKET),WTE,Unable to collect data for the field 'TR.COMPA...,Austria,Industrial Goods,...,Unable to collect data for the field 'TR.Capit...,Unable to collect data for the field 'TR.CashF...,Unable to collect data for the field 'TR.CashF...,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
493,FKAV.VI,Frauenthal Holding AG,Ordinary Shares,ORD,AT0000762406,WIENER BOERSE AG AMTLICHER HANDEL (OFFICIAL MA...,FKA,EUR,Austria,Industrial Conglomerates,...,-20568000,-39272000,14658000,"0,268972138","0,380733593","3,429030037","-0,03435618","-0,03435618","13,5643006","3,648418938"
494,MLTEA.EUA,Team SA,Ordinary Shares,ORD,FR0000033466,NYSE EURONEXT - MARCHE LIBRE PARIS,MLTEA,EUR,France,Industrial Goods,...,NaN,NaN,NaN,"0,054110492","1,947704913","0,284456558","0,366837925","0,366837925","25,39458443","1,374113461"
495,MEVr.AT,Mevaco SA,Ordinary Shares,ORD,GRS319103008,ATHENS EXCHANGE S.A. CASH MARKET,MEVA,EUR,Greece,Industrial Goods,...,-101710,-75070,-1136140,"0,111150283","3,660260619","0,390843055","-0,22530161","-0,22530161","14,03836547","1,560368293"
496,MCON.I,Mincon Group PLC,Ordinary Shares,ORD,IE00BD64C665,IRISH STOCK EXCHANGE - ALL MARKET,MIO,EUR,Ireland; Republic of,Industrial Goods,...,-6802000,-13917000,-4463000,"0,016891689","1,290753453","0,221085869","0,121331618","0,121331618","69,29395018","1,170491843"
497,PLAP.EUA,Placoplatre SA,Ordinary Shares,ORD,FR0000030769,NYSE EURONEXT - MARCHE LIBRE PARIS,MLPLC,EUR,France,Cyclical Consumer Products,...,NaN,NaN,NaN,"0,252833004","1,274490125","0,849261024","0,104747315","0,104747315","9,541926726","2,412513997"
498,HSTV.VI,Hutter & Schrantz Stahlbau AG,Ordinary Shares,ORD,AT0000A021K7,WIENER BOERSE AG DRITTER MARKT (THIRD MARKET),HST,EUR,Austria,Industrial & Commercial Services,...,-4330380,-4277340,-2651600,"0,231866737","0,557540128","1,415244905","0,162400853","0,162400853","9,238178099","2,142026216"
499,FOODr.AT,Foodlink SA,Ordinary Shares,ORD,GRS510003015,ATHENS EXCHANGE ALTERNATIVE MARKET,FOODL,EUR,Greece,Transportation,...,-1127720,-382500,-606830,"0,220156546","0,265487733","5,876297615","-0,128689576","-0,128689576","12,76224876","2,809692603"

In [161]:
data_frame.tail(12)

,code name,Company Common Name,Instrument Type,Asset Category Code,ISIN Code,Exchange Name,Ticker Symbol,Currency Code,Country of Headquarters,TRBC Business Sector Name,...,"Capital Expenditures, Cumulative","Cash from Investing Activities, Cumulative","Cash from Financing Activities, Cumulative",debt to asset ratio,equity to asset ratio,debt to equity ratio,Roa return on asset,roe return on equity,long term coverage ratio,asset turnover rate
540,MLV4S.EUA,Les Verandas 4 Saisons SA,Ordinary Shares,ORD,BE6201089735,NYSE EURONEXT - MARCHE LIBRE PARIS,MLV4S,NaN,Belgium,Cyclical Consumer Products,...,NaN,NaN,NaN,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
541,MLJSA.EUA,JSA Technology SA,Ordinary Shares,ORD,FR0010680033,NYSE EURONEXT - MARCHE LIBRE PARIS,MLJSA,NaN,France,Renewable Energy,...,NaN,NaN,NaN,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
542,MLKRI.EUA,Krief Group SA,Ordinary Shares,ORD,FR0004152700,NYSE EURONEXT - MARCHE LIBRE PARIS,MLKRI,NaN,France,Industrial & Commercial Services,...,NaN,NaN,NaN,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
543,1SES01AE.BV,Slovenske Energeticke Strojarne as,Ordinary Shares,ORD,SK1120008034,BRATISLAVA STOCK EXCHANGE,1SES01AE,EUR,Slovak Republic,Industrial Goods,...,-61000,2541000,5062000,"1,160404624","-0,068147247","-28,80078125","0,213682689","0,213682689","1,074752573","1,247147855"
544,LESr.AT,Maritime Company of Lesvos SA,Ordinary Shares,ORD,GRS243003019,ATHENS EXCHANGE S.A. CASH MARKET,NEL,EUR,Greece,Transportation,...,-7230,649130,1181350,"4,113031766","-1,128454118","-9,922083048","-3,259491636","-3,259491636","1,165266416","4,792777786"
545,LITF.EUL,Litho Formas SA,Ordinary Shares,ORD,PTLIT0AE0005,NYSE EURONEXT - EASYNEXT LISBON,LIT,EUR,Portugal,Industrial & Commercial Services,...,NaN,2770,-90640,"0,024471065","2,911877943","0,185978256","-0,089004112","-0,089004112","12,04578665","0,294773228"
546,CSSr.AT,Alpha Grissin Power and Environmental Control ...,Ordinary Shares,ORD,GRS480003003,ATHENS EXCHANGE S.A. CASH MARKET,AGRI,EUR,Greece,Software & IT Services,...,-32100,-36960,-624450,"0,002283448","-1,128915367","-3,273744712","-0,268891038","-0,268891038","594,8178408","1,358235834"
547,RER1R.RI,Rigas Elektromasinbuves Rupnica AS,Ordinary Shares,ORD,LV0000101012,NASDAQ OMX RIGA,RER1R,EUR,Latvia,Industrial Goods,...,-2043290,-1187660,-3980950,"0,279253132","2,425130488","0,544347861","0,045351043","0,045351043","9,068015378","2,532271695"
548,WOLFT.VI,Wolftank Adisa Holding AG,Ordinary Shares,ORD,AT0000A25NJ6,WIENER BOERSE AG DRITTER MARKT (THIRD MARKET),WOLF,Unable to collect data for the field 'TR.COMPA...,Austria,Industrial & Commercial Services,...,Unable to collect data for the field 'TR.Capit...,Unable to collect data for the field 'TR.CashF...,Unable to collect data for the field 'TR.CashF...,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!,#VALORE!
549,DESA.SCT,Desarrollos Especiales de Sistemas de Anclajes SA,Ordinary Shares,ORD,ES0126251018,BOLSA DE BARCELONA,DES,EUR,Spain,Industrial Goods,...,-1270330,-1073540,-830730,"0,185049376","0,552523925","2,02925994","0,040358368","0,040358368","9,936897486","1,838816684"
550,MLECO.EUA,Ecolutions GmbH & Co KGaA,Ordinary Shares,ORD,DE000A0XYM45,NYSE EURONEXT - MARCHE LIBRE PARIS,MLECO,EUR,Germany,Industrial & Commercial Services,...,NaN,NaN,NaN,0,"2,719228376","0,05816013","-0,041141691","-0,041141691",#DIV/0!,"0,181665051"
551,DPUY.EUA,Revival Expansion SA,Ordinary Shares,ORD,FR0000077232,NYSE EURONEXT - MARCHE LIBRE PARIS,MLGRD,EUR,France,Industrial & Commercial Services,...,NaN,NaN,NaN,"0,092113602","-18,46510737","-1,101081033","-0,06052969","-0,06052969","3,20208","0,294955122"

In [162]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 44 columns):
code name                                        552 non-null object
Company Common Name                              552 non-null object
Instrument Type                                  551 non-null object
Asset Category Code                              552 non-null object
ISIN Code                                        552 non-null object
Exchange Name                                    545 non-null object
Ticker Symbol                                    550 non-null object
Currency Code                                    534 non-null object
Country of Headquarters                          552 non-null object
TRBC Business Sector Name                        552 non-null object
Return On Equity - Actual                        308 non-null object
Return On Assets - Actual                        188 non-null object
Total Revenue                                    534 non-null object
Normalized EBIT                                  533 non-null object
Normalized EBITDA                                530 non-null object
Net Income Incl Extra Before Distributions       534 non-null object
Depreciation And Amortization                    479 non-null object
Selling/General/Administrative Expense, Total    527 non-null object
Total Current Assets                             532 non-null object
Total Liabilities                                532 non-null object
Total Current Liabilities                        531 non-null object
Total Equity                                     532 non-null object
Net Debt Incl. Pref.Stock & Min.Interest         532 non-null object
Total Assets, Reported                           532 non-null object
Total Long Term Debt                             531 non-null object
Cash                                             282 non-null object
Cash and Equivalents                             428 non-null object
Quick Ratio                                      532 non-null object
Current Ratio                                    532 non-null object
Accounts Payable                                 514 non-null object
Total Inventory                                  485 non-null object
Common Stock, Total                              530 non-null object
Property/Plant/Equipment, Total - Net            528 non-null object
Cash from Operating Activities, Cumulative       506 non-null object
Capital Expenditures, Cumulative                 495 non-null object
Cash from Investing Activities, Cumulative       506 non-null object
Cash from Financing Activities, Cumulative       505 non-null object
debt to asset ratio                              552 non-null object
equity to asset ratio                            552 non-null object
debt to equity ratio                             552 non-null object
Roa return on asset                              552 non-null object
roe return on equity                             552 non-null object
long term coverage ratio                         552 non-null object
asset turnover rate                              552 non-null object
dtypes: object(44)
memory usage: 189.8+ KB

In [123]:
#analysis data how many n/a data there is 
a=data_frame.isnull()
enumerate(a)
print(a)

     code name   Company Common Name  Instrument Type  Asset Category Code  \
0         False                False            False                False
1         False                False            False                False
2         False                False            False                False
3         False                False            False                False
4         False                False            False                False
5         False                False            False                False
6         False                False            False                False
7         False                False            False                False
8         False                False            False                False
9         False                False            False                False
10        False                False            False                False
11        False                False            False                False
12        False                False            False                False
13        False                False            False                False
14        False                False            False                False
15        False                False            False                False
16        False                False            False                False
17        False                False            False                False
18        False                False            False                False
19        False                False            False                False
20        False                False            False                False
21        False                False            False                False
22        False                False            False                False
23        False                False            False                False
24        False                False            False                False
25        False                False            False                False
26        False                False            False                False
27        False                False            False                False
28        False                False            False                False
29        False                False            False                False
..          ...                  ...              ...                  ...
522       False                False            False                False
523       False                False            False                False
524       False                False            False                False
525       False                False            False                False
526       False                False            False                False
527       False                False            False                False
528       False                False            False                False
529       False                False            False                False
530       False                False            False                False
531       False                False            False                False
532       False                False            False                False
533       False                False            False                False
534       False                False            False                False
535       False                False            False                False
536       False                False            False                False
537       False                False            False                False
538       False                False            False                False
539       False                False            False                False
540       False                False            False                False
541       False                False            False                False
542       False                False            False                False
543       False                False            False                False
544       False                False            False                False
545       False                False            False                False
546       False                False            False                False
547       False                False            False                False
548       False                False            False                False
549       False                False            False                False
550       False                False            False                False
551       False                False            False                False

     ISIN Code  Exchange Name  Ticker Symbol  Currency Code  \
0        False          False          False          False
1        False          False          False          False
2        False          False          False          False
3        False          False          False          False
4        False          False          False          False
5        False          False          False          False
6        False          False          False          False
7        False          False          False          False
8        False          False          False          False
9        False          False          False          False
10       False          False          False          False
11       False          False          False          False
12       False          False          False          False
13       False          False          False          False
14       False          False          False          False
15       False          False          False          False
16       False          False          False          False
17       False          False          False          False
18       False          False          False          False
19       False          False          False          False
20       False          False          False          False
21       False          False          False          False
22       False          False          False          False
23       False          False          False          False
24       False          False          False          False
25       False          False          False          False
26       False          False          False          False
27       False          False          False          False
28       False          False          False          False
29       False          False          False          False
..         ...            ...            ...            ...
522      False          False          False          False
523      False          False          False          False
524      False          False          False          False
525      False          False          False          False
526      False          False          False          False
527      False          False          False          False
528      False          False          False          False
529      False          False          False          False
530      False          False          False          False
531      False          False          False          False
532      False          False          False          False
533      False          False          False          False
534      False          False          False           True
535      False          False          False          False
536      False          False          False          False
537      False          False          False          False
538      False          False          False          False
539      False          False          False          False
540      False          False          False           True
541      False          False          False           True
542      False          False          False           True
543      False          False          False          False
544      False          False          False          False
545      False          False          False          False
546      False          False          False          False
547      False          False          False          False
548      False          False          False          False
549      False          False          False          False
550      False          False          False          False
551      False          False          False          False

     Country of Headquarters  TRBC Business Sector Name  ...  \
0                      False                      False  ...
1                      False                      False  ...
2                      False                      False  ...
3                      False                      False  ...
4                      False                      False  ...
5                      False                      False  ...
6                      False                      False  ...
7                      False                      False  ...
8                      False                      False  ...
9                      False                      False  ...
10                     False                      False  ...
11                     False                      False  ...
12                     False                      False  ...
13                     False                      False  ...
14                     False                      False  ...
15                     False                      False  ...
16                     False                      False  ...
17                     False                      False  ...
18                     False                      False  ...
19                     False                      False  ...
20                     False                      False  ...
21                     False                      False  ...
22                     False                      False  ...
23                     False                      False  ...
24                     False                      False  ...
25                     False                      False  ...
26                     False                      False  ...
27                     False                      False  ...
28                     False                      False  ...
29                     False                      False  ...
..                       ...                        ...  ...
522                    False                      False  ...
523                    False                      False  ...
524                    False                      False  ...
525                    False                      False  ...
526                    False                      False  ...
527                    False                      False  ...
528                    False                      False  ...
529                    False                      False  ...
530                    False                      False  ...
531                    False                      False  ...
532                    False                      False  ...
533                    False                      False  ...
534                    False                      False  ...
535                    False                      False  ...
536                    False                      False  ...
537                    False                      False  ...
538                    False                      False  ...
539                    False                      False  ...
540                    False                      False  ...
541                    False                      False  ...
542                    False                      False  ...
543                    False                      False  ...
544                    False                      False  ...
545                    False                      False  ...
546                    False                      False  ...
547                    False                      False  ...
548                    False                      False  ...
549                    False                      False  ...
550                    False                      False  ...
551                    False                      False  ...

     Capital Expenditures, Cumulative  \
0                               False
1                               False
2                               False
3                               False
4                               False
5                               False
6                               False
7                               False
8                               False
9                               False
10                              False
11                              False
12                              False
13                              False
14                              False
15                              False
16                              False
17                              False
18                              False
19                              False
20                              False
21                              False
22                              False
23                              False
24                              False
25                              False
26                              False
27                              False
28                              False
29                              False
..                                ...
522                             False
523                             False
524                             False
525                             False
526                             False
527                             False
528                             False
529                             False
530                              True
531                             False
532                             False
533                              True
534                              True
535                              True
536                              True
537                             False
538                              True
539                             False
540                              True
541                              True
542                              True
543                             False
544                             False
545                              True
546                             False
547                             False
548                             False
549                             False
550                              True
551                              True

     Cash from Investing Activities, Cumulative  \
0                                         False
1                                         False
2                                         False
3                                         False
4                                         False
5                                         False
6                                         False
7                                         False
8                                         False
9                                         False
10                                        False
11                                        False
12                                        False
13                                        False
14                                        False
15                                        False
16                                        False
17                                        False
18                                        False
19                                        False
20                                        False
21                                        False
22                                        False
23                                        False
24                                        False
25                                        False
26                                        False
27                                        False
28                                        False
29                                        False
..                                          ...
522                                       False
523                                       False
524                                       False
525                                       False
526                                       False
527                                       False
528                                       False
529                                       False
530                                        True
531                                       False
532                                       False
533                                        True
534                                        True
535                                        True
536                                        True
537                                       False
538                                       False
539                                       False
540                                        True
541                                        True
542                                        True
543                                       False
544                                       False
545                                       False
546                                       False
547                                       False
548                                       False
549                                       False
550                                        True
551                                        True

     Cash from Financing Activities, Cumulative  debt to asset ratio   \
0                                         False                 False
1                                         False                 False
2                                         False                 False
3                                         False                 False
4                                         False                 False
5                                         False                 False
6                                         False                 False
7                                         False                 False
8                                         False                 False
9                                         False                 False
10                                        False                 False
11                                        False                 False
12                                        False                 False
13                                        False                 False
14                                        False                 False
15                                        False                 False
16                                        False                 False
17                                        False                 False
18                                        False                 False
19                                        False                 False
20                                        False                 False
21                                        False                 False
22                                        False                 False
23                                        False                 False
24                                        False                 False
25                                        False                 False
26                                        False                 False
27                                        False                 False
28                                        False                 False
29                                        False                 False
..                                          ...                   ...
522                                       False                 False
523                                       False                 False
524                                       False                 False

In [115]:
data_frame.notnull()

,code name,Company Common Name,Instrument Type,Asset Category Code,ISIN Code,Exchange Name,Ticker Symbol,Currency Code,Country of Headquarters,TRBC Business Sector Name,...,"Capital Expenditures, Cumulative","Cash from Investing Activities, Cumulative","Cash from Financing Activities, Cumulative",debt to asset ratio,equity to asset ratio,debt to equity ratio,Roa return on asset,roe return on equity,long term coverage ratio,asset turnover rate
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
523,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
524,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
525,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
526,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
527,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
528,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
529,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
530,True,True,True,True,True,True,True,True,True,True,...,False,False,False,True,True,True,True,True,True,True
531,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
532,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
533,True,True,True,True,True,True,True,True,True,True,...,False,False,False,True,True,True,True,True,True,True
534,True,True,True,True,True,True,True,False,True,True,...,False,False,False,True,True,True,True,True,True,True
535,True,True,True,True,True,True,True,True,True,True,...,False,False,False,True,True,True,True,True,True,True
536,True,True,True,True,True,True,True,True,True,True,...,False,False,False,True,True,True,True,True,True,True
537,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
538,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
539,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
540,True,True,True,True,True,True,True,False,True,True,...,False,False,False,True,True,True,True,True,True,True
541,True,True,True,True,True,True,True,False,True,True,...,False,False,False,True,True,True,True,True,True,True
542,True,True,True,True,True,True,True,False,True,True,...,False,False,False,True,True,True,True,True,True,True
543,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
544,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
545,True,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True
546,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
547,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
548,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
549,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
550,True,True,True,True,True,True,True,True,True,True,...,False,False,False,True,True,True,True,True,True,True
551,True,True,True,True,True,True,True,True,True,True,...,False,False,False,True,True,True,True,True,True,True

In [119]:
#clean the data from the missing value 
cleardata=data_frame.dropna()
print(cleardata)

    code name                 Company Common Name    Instrument Type  \
4       SAF.PA                          Safran SA    Ordinary Shares
5     DPWGn.DE                   Deutsche Post AG    Ordinary Shares
8      BOUY.PA                        Bouygues SA    Ordinary Shares
10     TCFP.PA                          Thales SA    Ordinary Shares
15     AIRF.PA                  Air France KLM SA    Ordinary Shares
16     ALSO.PA                          Alstom SA    Ordinary Shares
22     FOUG.PA                         Eiffage SA    Ordinary Shares
25     AENA.MC                        Aena SME SA    Ordinary Shares
27     EDEN.PA                         Edenred SA    Ordinary Shares
30      BVI.PA                  Bureau Veritas SA    Ordinary Shares
42      ADP.PA              Aeroports de Paris SA    Ordinary Shares
45     AVMD.PA               Dassault Aviation SA    Ordinary Shares
50     ELIS.PA                            Elis SA    Ordinary Shares
51    WACGn.DE                   Wacker Neuson SE    Ordinary Shares
56     SIXG.DE                            Sixt SE    Ordinary Shares
57   JUNG_p.DE                    Jungheinrich AG  Preference Shares
60     KRNG.DE                          Krones AG    Ordinary Shares
78    INTER.AS                      Intertrust NV    Ordinary Shares
79      PSG.MC  Prosegur Compania de Seguridad SA    Ordinary Shares
83     ALDA.PA                             ALD SA    Ordinary Shares
90    HHFGn.DE    Hamburger Hafen und Logistik AG    Ordinary Shares
95     JSTG.DE                      JOST Werke AG    Ordinary Shares
97      CTT.LS        CTT Correios de Portugal SA    Ordinary Shares
102    CFEB.BR      Aannemingsmaatschappij Cfe NV    Ordinary Shares
113    CEVG.DE           Centrotec Sustainable AG    Ordinary Shares
164    AM3D.DE             SLM Solutions Group AG    Ordinary Shares
177    AVTX.AS                        Avantium NV    Ordinary Shares
201    FPHG.DE      Francotyp Postalia Holding AG    Ordinary Shares
235     TSSG.F                     InnoTec TSS AG    Ordinary Shares
263   ALSER.PA                     Serma Group SA    Ordinary Shares
318   ALIVA.PA                          Ivalis SA    Ordinary Shares
323    MTCM.MI                Maire Tecnimont SpA    Ordinary Shares
325    ENAV.MI                           Enav SpA    Ordinary Shares
338   METSO.HE                          Metso Oyj    Ordinary Shares
347   VALMT.HE                         Valmet Oyj    Ordinary Shares
395    KCRA.HE                     Konecranes Abp    Ordinary Shares
407   OTE1V.HE                        Outotec Oyj    Ordinary Shares
408   CGCBV.HE                       Cargotec Oyj    Ordinary Shares
452    MYTr.AT             Mytilineos Holdings SA    Ordinary Shares
457    HELr.AT                        Ellaktor SA    Ordinary Shares
462    AGNr.AT                 Aegean Airlines SA    Ordinary Shares
471    SMPV.VI                Semperit AG Holding    Ordinary Shares
482   MRK1T.TL                    Merko Ehitus AS    Ordinary Shares

    Asset Category Code     ISIN Code  \
4                   ORD  FR0000073272
5                   ORD  DE0005552004
8                   ORD  FR0000120503
10                  ORD  FR0000121329
15                  ORD  FR0000031122
16                  ORD  FR0010220475
22                  ORD  FR0000130452
25                  ORD  ES0105046009
27                  ORD  FR0010908533
30                  ORD  FR0006174348
42                  ORD  FR0010340141
45                  ORD  FR0000121725
50                  ORD  FR0012435121
51                  ORD  DE000WACK012
56                  ORD  DE0007231326
57                  PRF  DE0006219934
60                  ORD  DE0006335003
78                  ORD  NL0010937058
79                  ORD  ES0175438003
83                  ORD  FR0013258662
90                  ORD  DE000A0S8488
95                  ORD  DE000JST4000
97                  ORD  PTCTT0AM0001
102                 ORD  BE0003883031
113                 ORD  DE0005407506
164                 ORD  DE000A111338
177                 ORD  NL0012047823
201                 ORD  DE000FPH9000
235                 ORD  DE0005405104
263                 ORD  FR0000073728
318                 ORD  FR0010082305
323                 ORD  IT0004931058
325                 ORD  IT0005176406
338                 ORD  FI0009007835
347                 ORD  FI4000074984
395                 ORD  FI0009005870
407                 ORD  FI0009014575
408                 ORD  FI0009013429
452                 ORD  GRS393503008
457                 ORD  GRS191213008
462                 ORD  GRS495003006
471                 ORD  AT0000785555
482                 ORD  EE3100098328

                                         Exchange Name Ticker Symbol  \
4                       NYSE EURONEXT - EURONEXT PARIS           SAF
5                                                XETRA           DPW
8                       NYSE EURONEXT - EURONEXT PARIS            EN
10                      NYSE EURONEXT - EURONEXT PARIS            HO
15                      NYSE EURONEXT - EURONEXT PARIS            AF
16                      NYSE EURONEXT - EURONEXT PARIS           ALO
22                      NYSE EURONEXT - EURONEXT PARIS           FGR
25                                     BOLSA DE MADRID          AENA
27                      NYSE EURONEXT - EURONEXT PARIS          EDEN
30                      NYSE EURONEXT - EURONEXT PARIS           BVI
42                      NYSE EURONEXT - EURONEXT PARIS           ADP
45                      NYSE EURONEXT - EURONEXT PARIS            AM
50                      NYSE EURONEXT - EURONEXT PARIS          ELIS
51                                               XETRA           WAC
56                                               XETRA          SIX2
57                                               XETRA        giu-03
60                                               XETRA           KRN
78                  NYSE EURONEXT - EURONEXT AMSTERDAM         INTER
79                                     BOLSA DE MADRID           PSG
83                      NYSE EURONEXT - EURONEXT PARIS           ALD
90                                               XETRA          HHFA
95                                               XETRA           JST
97                     NYSE EURONEXT - EURONEXT LISBON           CTT
102                  NYSE EURONEXT - EURONEXT BRUSSELS          CFEB
113                                              XETRA           CEV
164                                              XETRA          AM3D
177                 NYSE EURONEXT - EURONEXT AMSTERDAM          AVTX
201                                              XETRA           FPH
235                                 DEUTSCHE BOERSE AG           TSS
263                    NYSE EURONEXT - ALTERNEXT PARIS         ALSER
318                    NYSE EURONEXT - ALTERNEXT PARIS         ALIVA
323                            ELECTRONIC SHARE MARKET            MT
325                            ELECTRONIC SHARE MARKET          ENAV
338                           NASDAQ OMX HELSINKI LTD.         METSO
347                           NASDAQ OMX HELSINKI LTD.         VALMT
395                           NASDAQ OMX HELSINKI LTD.           KCR
407                           NASDAQ OMX HELSINKI LTD.         OTE1V
408                           NASDAQ OMX HELSINKI LTD.         CGCBV
452                   ATHENS EXCHANGE S.A. CASH MARKET         MYTIL
457                   ATHENS EXCHANGE S.A. CASH MARKET      ELLAKTOR
462                   ATHENS EXCHANGE S.A. CASH MARKET          AEGN
471  WIENER BOERSE AG AMTLICHER HANDEL (OFFICIAL MA...           SEM
482                                 NASDAQ OMX TALLINN         MRK1T

    Currency Code   Country of Headquarters         TRBC Business Sector Name  \
4             EUR                    France                  Industrial Goods
5             EUR                   Germany                    Transportation
8             EUR                    France  Industrial & Commercial Services
10            EUR                    France                  Industrial Goods
15            EUR                    France                    Transportation
16            EUR                    France                  Industrial Goods
22            EUR                    France  Industrial & Commercial Services
25            EUR                     Spain                    Transportation
27            EUR                    France  Industrial & Commercial Services
30            EUR                    France  Industrial & Commercial Services
42            EUR                    France                    Transportation
45            EUR                    France                  Industrial Goods
50            EUR                    France  Industrial & Commercial Services
51            EUR                   Germany                  Industrial Goods
56            EUR                   Germany                    Transportation
57            EUR                   Germany                  Industrial Goods
60            EUR                   Germany                  Industrial Goods
78            EUR               Netherlands  Industrial & Commercial Services
79            EUR                     Spain  Industrial & Commercial Services
83            EUR                    France                    Transportation
90            EUR                   Germany                    Transportation
95            EUR                   Germany          Automobiles & Auto Parts
97            EUR                  Portugal                    Transportation
102           EUR                   Belgium  Industrial & Commercial Services
113           EUR                   Germany                  Industrial Goods
164           EUR                   Germany                  Industrial Goods
177           EUR               Netherlands  Industrial & Commercial Services
201           EUR                   Germany  Industrial & Commercial Services
235           EUR                   Germany        Cyclical Consumer Products
263           EUR                    France  Industrial & Commercial Services
318           EUR                    France  Industrial & Commercial Services
323           EUR                     Italy  Industrial & Commercial Services
325           EUR                     Italy                    Transportation
338           EUR                   Finland                  Industrial Goods
347           EUR                   Finland                  Industrial Goods
395           EUR                   Finland                  Industrial Goods
407           EUR                   Finland  Industrial & Commercial Services
408           EUR                   Finland                  Industrial Goods
452           EUR  United States of America          Industrial Conglomerates
457           EUR                    Greece  Industrial & Commercial Services
462           EUR                    Greece                    Transportation
471           EUR                   Austria          Automobiles & Auto Parts
482           EUR                   Estonia  Industrial & Commercial Services

     ... Capital Expenditures, Cumulative  \
4    ...                      -1089000000
5    ...                      -2203000000
8    ...                      -1931000000
10   ...                       -438900000
15   ...                      -2552000000
16   ...                       -293000000
22   ...                       -595000000
25   ...                       -370409000
27   ...                        -78000000
30   ...                       -142300000
42   ...                       -879000000
45   ...                        -76087000
50   ...                       -481900000
51   ...                        -47400000
56   ...                        -46212000
57   ...                       -109328000
60   ...                       -133566000
78   ...                         -8289000
79   ...                       -212941000
83   ...                        -64500000
90   ...                       -131962000
95   ...                        -19272000
97   ...                        -31219010
102  ...                       -458210000
113  ...                        -23315000
164  ...                        -21015000
177  ...                         -5016000
201  ...                        -15424000
235  ...                         -5189000
263  ...                         -3433000
318  ...                         -1152150
323  ...                         -3376000
325  ...                       -115377000
338  ...                        -38000000
347  ...                        -66000000
395  ...                        -28700000
407  ...                        -20900000
408  ...                        -84300000
452  ...                       -127496000
457  ...                        -95372000
462  ...                         -4709280
471  ...                        -74475000
482  ...                         -1367000

    Cash from Investing Activities, Cumulative  \
4                                   -334000000
5                                  -2091000000
8                                  -1481000000
10                                  -607700000
15                                 -2692000000
16                                  -353000000
22                                  -598000000
25                                  -361614000
27                                  -176000000
30                                  -312100000
42                                  -888000000
45                                   -98431000
50                                 -1841900000
51                                   -39000000
56                                   -45493000
57                                  -115165000
60                                  -144845000
78                                   -12775000
79                                  -733036000
83                                   -51300000
90                                  -131189000
95                                   -14781000
97                                  -240432690
102                                 -662933000
113                                 -115581000
164                                  -21418000
177                                   -5017000
201                                  -15474000
235                                    3168000
263                                   -4494000
318                                   -1229730
323                                  -19865000
325                                 -115016000
338                                  -66000000
347                                  -64000000
395                                 -542000000
407                                  -18900000
408                                  -89700000
452                                 -117203000
457                                  -59802000
462                                  -16673500
471                                   70520000
482                                     991000

    Cash from Financing Activities, Cumulative debt to asset ratio   \
4                                    393000000          0,203770965
5                                  -1087000000           0,34846842
8                                   -362000000          0,309728834
10                                  -381200000          0,064297949
15                                  -640000000          1,088430117
16                                  -305000000          0,166499785
22                                  -663000000          1,032282794
25                                 -1364274000           5,99422822
27                                  -264000000          0,384513858
30                                  -975100000          1,126873931
42                                  -114000000          1,680267772
45                                  -522842000          0,107701273
50                                  1492400000           1,63239604
51                                   -88200000          0,180484397
56                                    77638000          0,563195327
57                                   100861000           0,16002318
60                                   -24703000          2,78083E-06
78                                  -136622000          3,316730315
79                                   303739000          0,306147264
83                                  1835500000          3,077563527
90                                  -119024000          0,573209899
95                                   -27780000          0,623036998
97                                   -71947240          7,92118E-05
102                                  -54003000          0,355168769
113                                   80982000          0,444726085
164                                   74460000          0,531310809
177                                   96953000                    0
201                                    1091000          0,493248111
235                                   -2375000           0,23944206
263                                  -10481000          0,021508663
318                                    -250490          0,233111607
323                                  -54939000          0,111963576
325                                  -46094000          0,540912277
338                                 -134000000          0,238177128
347                                 -161000000          0,126415094
395                                  340000000          0,386789416
407                                  -12900000          0,218504406
408                                  -62600000          0,389164838
452                                 -132960000          0,442116619
457                                  -63321000          0,751912386
462                                  -38768940          0,045640399
471                                 -154899000          0,673020615
482                                    6089000          0,150183573

    equity to asset ratio  debt to equity ratio  Roa return on asset   \
4              0,499252217           2,464748048          0,243029591
5              0,856397398           2,060219989          0,183857414
8              0,483393058           3,016707236          0,057870247
10             0,331888006           3,764552898          0,045841369
15             0,265842349           11,44310631          0,017995142
16             0,482906594           2,923578199          0,052209984
22             0,365417376           5,999067599          0,046678024
25             4,681384733           1,693814169          1,014967413
27             -0,33150022          -5,121433311          0,053013638
30             0,488177885           4,513396538          0,154945166
42             1,459037297           2,119073629          0,182021039
45             0,409152002           3,035994017           0,06922221
50             2,312950495           1,727680559          0,032871287
51             1,298090359           0,449497668          0,101886353
56             0,350766059           3,241437279          0,063642384
57             0,665153211           2,319022187           0,09737543
60             0,617898915            1,28009835          0,087484497
78              3,03494685           1,472195348          0,380269259
79             0,456283029           2,576563279          0,064168302
83             1,041319756           5,307870646          0,175678603
90             1,172985797            2,21094741          0,166365332
95              0,73362398            1,97155728          -0,22025226
97             0,197620117           7,750699247          0,029306143
102            0,896508871           1,830185565          0,098524551
113            0,767688307           1,249542707          0,060111387

In [121]:
#new clean data 
print(cleardata)

    code name                 Company Common Name    Instrument Type  \
4       SAF.PA                          Safran SA    Ordinary Shares
5     DPWGn.DE                   Deutsche Post AG    Ordinary Shares
8      BOUY.PA                        Bouygues SA    Ordinary Shares
10     TCFP.PA                          Thales SA    Ordinary Shares
15     AIRF.PA                  Air France KLM SA    Ordinary Shares
16     ALSO.PA                          Alstom SA    Ordinary Shares
22     FOUG.PA                         Eiffage SA    Ordinary Shares
25     AENA.MC                        Aena SME SA    Ordinary Shares
27     EDEN.PA                         Edenred SA    Ordinary Shares
30      BVI.PA                  Bureau Veritas SA    Ordinary Shares
42      ADP.PA              Aeroports de Paris SA    Ordinary Shares
45     AVMD.PA               Dassault Aviation SA    Ordinary Shares
50     ELIS.PA                            Elis SA    Ordinary Shares
51    WACGn.DE                   Wacker Neuson SE    Ordinary Shares
56     SIXG.DE                            Sixt SE    Ordinary Shares
57   JUNG_p.DE                    Jungheinrich AG  Preference Shares
60     KRNG.DE                          Krones AG    Ordinary Shares
78    INTER.AS                      Intertrust NV    Ordinary Shares
79      PSG.MC  Prosegur Compania de Seguridad SA    Ordinary Shares
83     ALDA.PA                             ALD SA    Ordinary Shares
90    HHFGn.DE    Hamburger Hafen und Logistik AG    Ordinary Shares
95     JSTG.DE                      JOST Werke AG    Ordinary Shares
97      CTT.LS        CTT Correios de Portugal SA    Ordinary Shares
102    CFEB.BR      Aannemingsmaatschappij Cfe NV    Ordinary Shares
113    CEVG.DE           Centrotec Sustainable AG    Ordinary Shares
164    AM3D.DE             SLM Solutions Group AG    Ordinary Shares
177    AVTX.AS                        Avantium NV    Ordinary Shares
201    FPHG.DE      Francotyp Postalia Holding AG    Ordinary Shares
235     TSSG.F                     InnoTec TSS AG    Ordinary Shares
263   ALSER.PA                     Serma Group SA    Ordinary Shares
318   ALIVA.PA                          Ivalis SA    Ordinary Shares
323    MTCM.MI                Maire Tecnimont SpA    Ordinary Shares
325    ENAV.MI                           Enav SpA    Ordinary Shares
338   METSO.HE                          Metso Oyj    Ordinary Shares
347   VALMT.HE                         Valmet Oyj    Ordinary Shares
395    KCRA.HE                     Konecranes Abp    Ordinary Shares
407   OTE1V.HE                        Outotec Oyj    Ordinary Shares
408   CGCBV.HE                       Cargotec Oyj    Ordinary Shares
452    MYTr.AT             Mytilineos Holdings SA    Ordinary Shares
457    HELr.AT                        Ellaktor SA    Ordinary Shares
462    AGNr.AT                 Aegean Airlines SA    Ordinary Shares
471    SMPV.VI                Semperit AG Holding    Ordinary Shares
482   MRK1T.TL                    Merko Ehitus AS    Ordinary Shares

    Asset Category Code     ISIN Code  \
4                   ORD  FR0000073272
5                   ORD  DE0005552004
8                   ORD  FR0000120503
10                  ORD  FR0000121329
15                  ORD  FR0000031122
16                  ORD  FR0010220475
22                  ORD  FR0000130452
25                  ORD  ES0105046009
27                  ORD  FR0010908533
30                  ORD  FR0006174348
42                  ORD  FR0010340141
45                  ORD  FR0000121725
50                  ORD  FR0012435121
51                  ORD  DE000WACK012
56                  ORD  DE0007231326
57                  PRF  DE0006219934
60                  ORD  DE0006335003
78                  ORD  NL0010937058
79                  ORD  ES0175438003
83                  ORD  FR0013258662
90                  ORD  DE000A0S8488
95                  ORD  DE000JST4000
97                  ORD  PTCTT0AM0001
102                 ORD  BE0003883031
113                 ORD  DE0005407506
164                 ORD  DE000A111338
177                 ORD  NL0012047823
201                 ORD  DE000FPH9000
235                 ORD  DE0005405104
263                 ORD  FR0000073728
318                 ORD  FR0010082305
323                 ORD  IT0004931058
325                 ORD  IT0005176406
338                 ORD  FI0009007835
347                 ORD  FI4000074984
395                 ORD  FI0009005870
407                 ORD  FI0009014575
408                 ORD  FI0009013429
452                 ORD  GRS393503008
457                 ORD  GRS191213008
462                 ORD  GRS495003006
471                 ORD  AT0000785555
482                 ORD  EE3100098328

                                         Exchange Name Ticker Symbol  \
4                       NYSE EURONEXT - EURONEXT PARIS           SAF
5                                                XETRA           DPW
8                       NYSE EURONEXT - EURONEXT PARIS            EN
10                      NYSE EURONEXT - EURONEXT PARIS            HO
15                      NYSE EURONEXT - EURONEXT PARIS            AF
16                      NYSE EURONEXT - EURONEXT PARIS           ALO
22                      NYSE EURONEXT - EURONEXT PARIS           FGR
25                                     BOLSA DE MADRID          AENA
27                      NYSE EURONEXT - EURONEXT PARIS          EDEN
30                      NYSE EURONEXT - EURONEXT PARIS           BVI
42                      NYSE EURONEXT - EURONEXT PARIS           ADP
45                      NYSE EURONEXT - EURONEXT PARIS            AM
50                      NYSE EURONEXT - EURONEXT PARIS          ELIS
51                                               XETRA           WAC
56                                               XETRA          SIX2
57                                               XETRA        giu-03
60                                               XETRA           KRN
78                  NYSE EURONEXT - EURONEXT AMSTERDAM         INTER
79                                     BOLSA DE MADRID           PSG
83                      NYSE EURONEXT - EURONEXT PARIS           ALD
90                                               XETRA          HHFA
95                                               XETRA           JST
97                     NYSE EURONEXT - EURONEXT LISBON           CTT
102                  NYSE EURONEXT - EURONEXT BRUSSELS          CFEB
113                                              XETRA           CEV
164                                              XETRA          AM3D
177                 NYSE EURONEXT - EURONEXT AMSTERDAM          AVTX
201                                              XETRA           FPH
235                                 DEUTSCHE BOERSE AG           TSS
263                    NYSE EURONEXT - ALTERNEXT PARIS         ALSER
318                    NYSE EURONEXT - ALTERNEXT PARIS         ALIVA
323                            ELECTRONIC SHARE MARKET            MT
325                            ELECTRONIC SHARE MARKET          ENAV
338                           NASDAQ OMX HELSINKI LTD.         METSO
347                           NASDAQ OMX HELSINKI LTD.         VALMT
395                           NASDAQ OMX HELSINKI LTD.           KCR
407                           NASDAQ OMX HELSINKI LTD.         OTE1V
408                           NASDAQ OMX HELSINKI LTD.         CGCBV
452                   ATHENS EXCHANGE S.A. CASH MARKET         MYTIL
457                   ATHENS EXCHANGE S.A. CASH MARKET      ELLAKTOR
462                   ATHENS EXCHANGE S.A. CASH MARKET          AEGN
471  WIENER BOERSE AG AMTLICHER HANDEL (OFFICIAL MA...           SEM
482                                 NASDAQ OMX TALLINN         MRK1T

    Currency Code   Country of Headquarters         TRBC Business Sector Name  \
4             EUR                    France                  Industrial Goods
5             EUR                   Germany                    Transportation
8             EUR                    France  Industrial & Commercial Services
10            EUR                    France                  Industrial Goods
15            EUR                    France                    Transportation
16            EUR                    France                  Industrial Goods
22            EUR                    France  Industrial & Commercial Services
25            EUR                     Spain                    Transportation
27            EUR                    France  Industrial & Commercial Services
30            EUR                    France  Industrial & Commercial Services
42            EUR                    France                    Transportation
45            EUR                    France                  Industrial Goods
50            EUR                    France  Industrial & Commercial Services
51            EUR                   Germany                  Industrial Goods
56            EUR                   Germany                    Transportation
57            EUR                   Germany                  Industrial Goods
60            EUR                   Germany                  Industrial Goods
78            EUR               Netherlands  Industrial & Commercial Services
79            EUR                     Spain  Industrial & Commercial Services
83            EUR                    France                    Transportation
90            EUR                   Germany                    Transportation
95            EUR                   Germany          Automobiles & Auto Parts
97            EUR                  Portugal                    Transportation
102           EUR                   Belgium  Industrial & Commercial Services
113           EUR                   Germany                  Industrial Goods
164           EUR                   Germany                  Industrial Goods
177           EUR               Netherlands  Industrial & Commercial Services
201           EUR                   Germany  Industrial & Commercial Services
235           EUR                   Germany        Cyclical Consumer Products
263           EUR                    France  Industrial & Commercial Services
318           EUR                    France  Industrial & Commercial Services
323           EUR                     Italy  Industrial & Commercial Services
325           EUR                     Italy                    Transportation
338           EUR                   Finland                  Industrial Goods
347           EUR                   Finland                  Industrial Goods
395           EUR                   Finland                  Industrial Goods
407           EUR                   Finland  Industrial & Commercial Services
408           EUR                   Finland                  Industrial Goods
452           EUR  United States of America          Industrial Conglomerates
457           EUR                    Greece  Industrial & Commercial Services
462           EUR                    Greece                    Transportation
471           EUR                   Austria          Automobiles & Auto Parts
482           EUR                   Estonia  Industrial & Commercial Services

     ... Capital Expenditures, Cumulative  \
4    ...                      -1089000000
5    ...                      -2203000000
8    ...                      -1931000000
10   ...                       -438900000
15   ...                      -2552000000
16   ...                       -293000000
22   ...                       -595000000
25   ...                       -370409000
27   ...                        -78000000
30   ...                       -142300000
42   ...                       -879000000
45   ...                        -76087000
50   ...                       -481900000
51   ...                        -47400000
56   ...                        -46212000
57   ...                       -109328000
60   ...                       -133566000
78   ...                         -8289000
79   ...                       -212941000
83   ...                        -64500000
90   ...                       -131962000
95   ...                        -19272000
97   ...                        -31219010
102  ...                       -458210000
113  ...                        -23315000
164  ...                        -21015000
177  ...                         -5016000
201  ...                        -15424000
235  ...                         -5189000
263  ...                         -3433000
318  ...                         -1152150
323  ...                         -3376000
325  ...                       -115377000
338  ...                        -38000000
347  ...                        -66000000
395  ...                        -28700000
407  ...                        -20900000
408  ...                        -84300000
452  ...                       -127496000
457  ...                        -95372000
462  ...                         -4709280
471  ...                        -74475000
482  ...                         -1367000

    Cash from Investing Activities, Cumulative  \
4                                   -334000000
5                                  -2091000000
8                                  -1481000000
10                                  -607700000
15                                 -2692000000
16                                  -353000000
22                                  -598000000
25                                  -361614000
27                                  -176000000
30                                  -312100000
42                                  -888000000
45                                   -98431000
50                                 -1841900000
51                                   -39000000
56                                   -45493000
57                                  -115165000
60                                  -144845000
78                                   -12775000
79                                  -733036000
83                                   -51300000
90                                  -131189000
95                                   -14781000
97                                  -240432690
102                                 -662933000
113                                 -115581000
164                                  -21418000
177                                   -5017000
201                                  -15474000
235                                    3168000
263                                   -4494000
318                                   -1229730
323                                  -19865000
325                                 -115016000
338                                  -66000000
347                                  -64000000
395                                 -542000000
407                                  -18900000
408                                  -89700000
452                                 -117203000
457                                  -59802000
462                                  -16673500
471                                   70520000
482                                     991000

    Cash from Financing Activities, Cumulative debt to asset ratio   \
4                                    393000000          0,203770965
5                                  -1087000000           0,34846842
8                                   -362000000          0,309728834
10                                  -381200000          0,064297949
15                                  -640000000          1,088430117
16                                  -305000000          0,166499785
22                                  -663000000          1,032282794
25                                 -1364274000           5,99422822
27                                  -264000000          0,384513858
30                                  -975100000          1,126873931
42                                  -114000000          1,680267772
45                                  -522842000          0,107701273
50                                  1492400000           1,63239604
51                                   -88200000          0,180484397
56                                    77638000          0,563195327
57                                   100861000           0,16002318
60                                   -24703000          2,78083E-06
78                                  -136622000          3,316730315
79                                   303739000          0,306147264
83                                  1835500000          3,077563527
90                                  -119024000          0,573209899
95                                   -27780000          0,623036998
97                                   -71947240          7,92118E-05
102                                  -54003000          0,355168769
113                                   80982000          0,444726085
164                                   74460000          0,531310809
177                                   96953000                    0
201                                    1091000          0,493248111
235                                   -2375000           0,23944206
263                                  -10481000          0,021508663
318                                    -250490          0,233111607
323                                  -54939000          0,111963576
325                                  -46094000          0,540912277
338                                 -134000000          0,238177128
347                                 -161000000          0,126415094
395                                  340000000          0,386789416
407                                  -12900000          0,218504406
408                                  -62600000          0,389164838
452                                 -132960000          0,442116619
457                                  -63321000          0,751912386
462                                  -38768940          0,045640399
471                                 -154899000          0,673020615
482                                    6089000          0,150183573

    equity to asset ratio  debt to equity ratio  Roa return on asset   \
4              0,499252217           2,464748048          0,243029591
5              0,856397398           2,060219989          0,183857414
8              0,483393058           3,016707236          0,057870247
10             0,331888006           3,764552898          0,045841369
15             0,265842349           11,44310631          0,017995142
16             0,482906594           2,923578199          0,052209984
22             0,365417376           5,999067599          0,046678024
25             4,681384733           1,693814169          1,014967413
27             -0,33150022          -5,121433311          0,053013638
30             0,488177885           4,513396538          0,154945166
42             1,459037297           2,119073629          0,182021039
45             0,409152002           3,035994017           0,06922221
50             2,312950495           1,727680559          0,032871287
51             1,298090359           0,449497668          0,101886353
56             0,350766059           3,241437279          0,063642384
57             0,665153211           2,319022187           0,09737543
60             0,617898915            1,28009835          0,087484497
78              3,03494685           1,472195348          0,380269259
79             0,456283029           2,576563279          0,064168302
83             1,041319756           5,307870646          0,175678603
90             1,172985797            2,21094741          0,166365332
95              0,73362398            1,97155728          -0,22025226
97             0,197620117           7,750699247          0,029306143
102            0,896508871           1,830185565          0,098524551
113            0,767688307           1,249542707          0,060111387

In [126]:
cleardata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43 entries, 4 to 482
Data columns (total 44 columns):
code name                                        43 non-null object
Company Common Name                              43 non-null object
Instrument Type                                  43 non-null object
Asset Category Code                              43 non-null object
ISIN Code                                        43 non-null object
Exchange Name                                    43 non-null object
Ticker Symbol                                    43 non-null object
Currency Code                                    43 non-null object
Country of Headquarters                          43 non-null object
TRBC Business Sector Name                        43 non-null object
Return On Equity - Actual                        43 non-null object
Return On Assets - Actual                        43 non-null object
Total Revenue                                    43 non-null object
Normalized EBIT                                  43 non-null object
Normalized EBITDA                                43 non-null object
Net Income Incl Extra Before Distributions       43 non-null object
Depreciation And Amortization                    43 non-null object
Selling/General/Administrative Expense, Total    43 non-null object
Total Current Assets                             43 non-null object
Total Liabilities                                43 non-null object
Total Current Liabilities                        43 non-null object
Total Equity                                     43 non-null object
Net Debt Incl. Pref.Stock & Min.Interest         43 non-null object
Total Assets, Reported                           43 non-null object
Total Long Term Debt                             43 non-null object
Cash                                             43 non-null object
Cash and Equivalents                             43 non-null object
Quick Ratio                                      43 non-null object
Current Ratio                                    43 non-null object
Accounts Payable                                 43 non-null object
Total Inventory                                  43 non-null object
Common Stock, Total                              43 non-null object
Property/Plant/Equipment, Total - Net            43 non-null object
Cash from Operating Activities, Cumulative       43 non-null object
Capital Expenditures, Cumulative                 43 non-null object
Cash from Investing Activities, Cumulative       43 non-null object
Cash from Financing Activities, Cumulative       43 non-null object
debt to asset ratio                              43 non-null object
equity to asset ratio                            43 non-null object
debt to equity ratio                             43 non-null object
Roa return on asset                              43 non-null object
roe return on equity                             43 non-null object
long term coverage ratio                         43 non-null object
asset turnover rate                              43 non-null object
dtypes: object(44)
memory usage: 15.1+ KB

In [127]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 44 columns):
code name                                        552 non-null object
Company Common Name                              552 non-null object
Instrument Type                                  551 non-null object
Asset Category Code                              552 non-null object
ISIN Code                                        552 non-null object
Exchange Name                                    545 non-null object
Ticker Symbol                                    550 non-null object
Currency Code                                    534 non-null object
Country of Headquarters                          552 non-null object
TRBC Business Sector Name                        552 non-null object
Return On Equity - Actual                        308 non-null object
Return On Assets - Actual                        188 non-null object
Total Revenue                                    534 non-null object
Normalized EBIT                                  533 non-null object
Normalized EBITDA                                530 non-null object
Net Income Incl Extra Before Distributions       534 non-null object
Depreciation And Amortization                    479 non-null object
Selling/General/Administrative Expense, Total    527 non-null object
Total Current Assets                             532 non-null object
Total Liabilities                                532 non-null object
Total Current Liabilities                        531 non-null object
Total Equity                                     532 non-null object
Net Debt Incl. Pref.Stock & Min.Interest         532 non-null object
Total Assets, Reported                           532 non-null object
Total Long Term Debt                             531 non-null object
Cash                                             282 non-null object
Cash and Equivalents                             428 non-null object
Quick Ratio                                      532 non-null object
Current Ratio                                    532 non-null object
Accounts Payable                                 514 non-null object
Total Inventory                                  485 non-null object
Common Stock, Total                              530 non-null object
Property/Plant/Equipment, Total - Net            528 non-null object
Cash from Operating Activities, Cumulative       506 non-null object
Capital Expenditures, Cumulative                 495 non-null object
Cash from Investing Activities, Cumulative       506 non-null object
Cash from Financing Activities, Cumulative       505 non-null object
debt to asset ratio                              552 non-null object
equity to asset ratio                            552 non-null object
debt to equity ratio                             552 non-null object
Roa return on asset                              552 non-null object
roe return on equity                             552 non-null object
long term coverage ratio                         552 non-null object
asset turnover rate                              552 non-null object
dtypes: object(44)
memory usage: 189.8+ KB

In [128]:
filldata=data_frame.fillna(1)

In [129]:
filldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 552 entries, 0 to 551
Data columns (total 44 columns):
code name                                        552 non-null object
Company Common Name                              552 non-null object
Instrument Type                                  552 non-null object
Asset Category Code                              552 non-null object
ISIN Code                                        552 non-null object
Exchange Name                                    552 non-null object
Ticker Symbol                                    552 non-null object
Currency Code                                    552 non-null object
Country of Headquarters                          552 non-null object
TRBC Business Sector Name                        552 non-null object
Return On Equity - Actual                        552 non-null object
Return On Assets - Actual                        552 non-null object
Total Revenue                                    552 non-null object
Normalized EBIT                                  552 non-null object
Normalized EBITDA                                552 non-null object
Net Income Incl Extra Before Distributions       552 non-null object
Depreciation And Amortization                    552 non-null object
Selling/General/Administrative Expense, Total    552 non-null object
Total Current Assets                             552 non-null object
Total Liabilities                                552 non-null object
Total Current Liabilities                        552 non-null object
Total Equity                                     552 non-null object
Net Debt Incl. Pref.Stock & Min.Interest         552 non-null object
Total Assets, Reported                           552 non-null object
Total Long Term Debt                             552 non-null object
Cash                                             552 non-null object
Cash and Equivalents                             552 non-null object
Quick Ratio                                      552 non-null object
Current Ratio                                    552 non-null object
Accounts Payable                                 552 non-null object
Total Inventory                                  552 non-null object
Common Stock, Total                              552 non-null object
Property/Plant/Equipment, Total - Net            552 non-null object
Cash from Operating Activities, Cumulative       552 non-null object
Capital Expenditures, Cumulative                 552 non-null object
Cash from Investing Activities, Cumulative       552 non-null object
Cash from Financing Activities, Cumulative       552 non-null object
debt to asset ratio                              552 non-null object
equity to asset ratio                            552 non-null object
debt to equity ratio                             552 non-null object
Roa return on asset                              552 non-null object
roe return on equity                             552 non-null object
long term coverage ratio                         552 non-null object
asset turnover rate                              552 non-null object
dtypes: object(44)
memory usage: 189.8+ KB

In [165]:
filldata.columns[3]

'Asset Category Code'

In [187]:
print(filldata.count())

code name                                        552
Company Common Name                              552
Instrument Type                                  552
Asset Category Code                              552
ISIN Code                                        552
Exchange Name                                    552
Ticker Symbol                                    552
Currency Code                                    552
Country of Headquarters                          552
TRBC Business Sector Name                        552
Return On Equity - Actual                        552
Return On Assets - Actual                        552
Total Revenue                                    552
Normalized EBIT                                  552
Normalized EBITDA                                552
Net Income Incl Extra Before Distributions       552
Depreciation And Amortization                    552
Selling/General/Administrative Expense, Total    552
Total Current Assets                             552
Total Liabilities                                552
Total Current Liabilities                        552
Total Equity                                     552
Net Debt Incl. Pref.Stock & Min.Interest         552
Total Assets, Reported                           552
Total Long Term Debt                             552
Cash                                             552
Cash and Equivalents                             552
Quick Ratio                                      552
Current Ratio                                    552
Accounts Payable                                 552
Total Inventory                                  552
Common Stock, Total                              552
Property/Plant/Equipment, Total - Net            552
Cash from Operating Activities, Cumulative       552
Capital Expenditures, Cumulative                 552
Cash from Investing Activities, Cumulative       552
Cash from Financing Activities, Cumulative       552
debt to asset ratio                              552
equity to asset ratio                            552
debt to equity ratio                             552
Roa return on asset                              552
roe return on equity                             552
long term coverage ratio                         552
asset turnover rate                              552
dtype: int64

In [1]:
data_frame.value()

NameError: name 'data_frame' is not defined